// Tiny Tides — game content.
// Everything tunable lives here: the sky palettes, every fish, every piece of
// clothing, and the fishing gear. Change a number or a colour here and the
// rest of the game picks it up.

const OUTLINE = '#2a1a2e';

// ---------------------------------------------------------------- the sky --
// The day loops sunrise -> day -> golden hour -> sunset -> dusk -> night -> ...
// Each phase lasts PHASE_SECONDS; the last 30% of a phase blends into the next.
// sunX / sunY: where the sun sits (it travels left to right across the day).
const PHASE_SECONDS = 65;

const PHASES = [
  {
    id: 'sunrise', arrive: 'Good morning! The sun is rising', name: 'Sunrise',
    sky: ['#4a5a9a', '#8a74b0', '#d890b0', '#ffb0a0', '#ffc8a0', '#ffe0b0', '#fff0d0'],
    water: ['#e8b0b8', '#a88ab8', '#6a6aa0', '#443e78'],
    refl: '#ffe8c0', sun: '#ffe0b0', sunX: 84, sunY: 80,
    hillsFar: '#b08ab0', hills: '#7a5a90', cloud: '#ffe8e0', cloudShade: '#f0a8b8',
    stars: 0.12, lamp: 0.3, moon: 0, night: 0.1,
  },
  {
    id: 'day', arrive: 'Bright blue skies. Day fish are out!', name: 'Daytime',
    sky: ['#5aa0e0', '#6eaee6', '#86bcec', '#9ecaf0', '#b6d8f2', '#cee6f2', '#e6f2ee'],
    water: ['#8ad0e0', '#5aaad0', '#3a82b4', '#2a5a8e'],
    refl: '#ffffff', sun: '#fff8e0', sunX: 150, sunY: 24,
    hillsFar: '#9ac4b4', hills: '#6a9a7e', cloud: '#ffffff', cloudShade: '#cce0f4',
    stars: 0, lamp: 0, moon: 0, night: 0,
  },
  {
    id: 'golden', arrive: 'The light turns golden', name: 'Golden hour',
    sky: ['#7a64b0', '#a672b8', '#e08aa8', '#f7a88a', '#ffc88a', '#ffe0a0', '#fff0c4'],
    water: ['#f2a8a0', '#c47aa8', '#8a5a9a', '#5e3f7e'],
    refl: '#fff3c4', sun: '#fff3c4', sunX: 205, sunY: 58,
    hillsFar: '#d58aa6', hills: '#a0508a', cloud: '#fff0dc', cloudShade: '#f5a8a0',
    stars: 0, lamp: 0, moon: 0, night: 0,
  },
  {
    id: 'sunset', arrive: 'The sun is setting...', name: 'Sunset',
    sky: ['#3d2a6b', '#7a3a7a', '#c4507a', '#f0706a', '#ff9a5c', '#ffc05c', '#ffe08a'],
    water: ['#e8808a', '#a24c86', '#62306e', '#3e2256'],
    refl: '#ffd27a', sun: '#ffd27a', sunX: 228, sunY: 84,
    hillsFar: '#b0507a', hills: '#7a3470', cloud: '#ffc4a4', cloudShade: '#e0708a',
    stars: 0.1, lamp: 0.4, moon: 0, night: 0.15,
  },
  {
    id: 'dusk', arrive: 'Dusk settles in. Night fish are stirring!', name: 'Dusk',
    sky: ['#1e1a45', '#3a2560', '#6a3070', '#a8407a', '#e0607a', '#f59070', '#ffb880'],
    water: ['#9a5282', '#5e306a', '#34204e', '#221638'],
    refl: '#ff9a6a', sun: '#ff9a6a', sunX: 236, sunY: 104,
    hillsFar: '#6a3070', hills: '#3a2458', cloud: '#c47aa0', cloudShade: '#7a4a8a',
    stars: 0.55, lamp: 1, moon: 0.35, night: 0.55,
  },
  {
    id: 'night', arrive: 'Night has fallen. The stars are out', name: 'Night',
    sky: ['#0e0e2a', '#141440', '#1c1a50', '#26205c', '#342866', '#44306e', '#553876'],
    water: ['#3a2e6a', '#241e50', '#16123a', '#0e0b28'],
    refl: '#efe6ff', sun: '#ff9a6a', sunX: 84, sunY: 140,
    hillsFar: '#241e50', hills: '#15133a', cloud: '#4a3a78', cloudShade: '#2e2658',
    stars: 1, lamp: 1, moon: 1, night: 1,
  },
];

// ------------------------------------------------------------ the places --
// need: how many fish (not junk) you must have caught before the boat can take
// you there. tint pulls the sky and water toward a colour, by `amount`.
// map: where the island sits on the 160x100 sea chart.
const LOCATIONS = [
  { id: 'dock', name: 'Sunset Dock', need: 0, platform: 'dock', landmark: 'lighthouse', props: 'reeds',
    tint: null, map: { x: 22, y: 80 },
    blurb: 'Home sweet home. A creaky dock, a lantern, and a lighthouse winking across the water.' },
  { id: 'lagoon', name: 'Lily Lagoon', need: 12, platform: 'boat', landmark: 'willow', props: 'lilies',
    tint: { sky: '#ffb4d4', water: '#78c8a0', amount: 0.24 }, map: { x: 40, y: 42 },
    blurb: 'A still, pink lagoon full of lily pads, under a sleepy old willow.' },
  { id: 'cove', name: 'Coral Cove', need: 30, platform: 'boat', landmark: 'palms', props: 'coral',
    tint: { sky: '#ffc880', water: '#30b8c4', amount: 0.34 }, map: { x: 72, y: 72 },
    blurb: 'Warm, clear sea over pink coral. Watch out for pinchy things.' },
  { id: 'bay', name: 'Aurora Bay', need: 55, platform: 'boat', landmark: 'icebergs', props: 'ice',
    tint: { sky: '#a8d8ff', water: '#7aaae0', amount: 0.32 }, map: { x: 82, y: 20 },
    blurb: 'Far to the north. Icebergs, snowflakes, and ribbons of light at night.' },
  { id: 'blossom', name: 'Blossom River', need: 80, platform: 'boat', landmark: 'sakura', props: 'petals',
    tint: { sky: '#ffc4dc', water: '#a4c8e8', amount: 0.26 }, map: { x: 114, y: 46 },
    blurb: 'A slow river under cherry trees. Petals land on the water like tiny boats.' },
  { id: 'ember', name: 'Ember Isle', need: 110, platform: 'boat', landmark: 'volcano', props: 'embers',
    tint: { sky: '#ff9a6a', water: '#3a6a78', amount: 0.3 }, map: { x: 136, y: 80 },
    blurb: 'A sleepy volcano puffs smoke rings. The water is warm and a little sparkly.' },
  { id: 'cloud', name: 'Cloud Lake', need: 150, platform: 'boat', landmark: 'floating', props: 'mist',
    tint: { sky: '#c4e2ff', water: '#a4d4ff', amount: 0.36 }, map: { x: 140, y: 16 },
    blurb: 'A lake so still it holds the sky. Little islands float overhead.' },
];

// -------------------------------------------------------------- the fish --
// reel: how each tier fights on the line. speed scales how fast it swims,
// gain how fast the catch bar fills while it's in your net, drain how fast
// the bar empties while it's out.
const RARITY = {
  junk:      { label: 'Junk',      weight: 9,  color: '#b8a89a', biteWindow: 1.0,  reel: { speed: 0.7,  gain: 1.4,  drain: 0.6 } },
  common:    { label: 'Common',    weight: 58, color: '#fff4e0', biteWindow: 0.95, reel: { speed: 1,    gain: 1,    drain: 1 } },
  uncommon:  { label: 'Uncommon',  weight: 22, color: '#8fd19e', biteWindow: 0.85, reel: { speed: 1.03, gain: 0.85, drain: 1.1 } },
  rare:      { label: 'Rare',      weight: 8,  color: '#7fb8e6', biteWindow: 0.75, reel: { speed: 1.06, gain: 0.72, drain: 1.2 } },
  legendary: { label: 'Legendary', weight: 2.5, color: '#ffd23f', biteWindow: 0.65, reel: { speed: 1.1,  gain: 0.6,  drain: 1.35 } },
  // weight 0: nothing is caught by being 'goat' tier alone; LeBron sets his own weight below
  goat:      { label: 'The GOAT', weight: 0, color: '#c79bf2', biteWindow: 0.8,  reel: { speed: 1.12, gain: 0.55, drain: 1.45 } },
};

const ALL_DAY = ['sunrise', 'day', 'golden', 'sunset', 'dusk', 'night'];
const EVERYWHERE = ['dock', 'lagoon', 'cove', 'bay', 'blossom', 'ember', 'cloud'];

// where: which locations it lives in (leave it out for Sunset Dock only)
// weight: optional fixed catch weight, overriding the rarity's (see LeBron)
// bottom: in the aquarium it walks along the sand instead of swimming
// unsellable: can never be sold, only kept in the tank (where he always fits)
// shape: 'fish' (default), 'round', 'eel', 'puffer', or map: a pixel map in sprites.js
// pattern: none | stripes | spots | patches | stars | gradient
// diff: how hard it fights on the line (1 = sleepy, 6 = feral)
const FISH = [
  { id: 'boot', name: 'Soggy Boot', rarity: 'junk', price: 2, phases: ALL_DAY, diff: 0.6, where: EVERYWHERE,
    size: [24, 30], map: 'boot', bottom: true,
    blurb: 'Somebody out there is hopping around on one foot.' },
  { id: 'can', name: 'Tin Can', rarity: 'junk', price: 1, phases: ALL_DAY, diff: 0.6, where: EVERYWHERE,
    size: [8, 12], map: 'can', bottom: true,
    blurb: 'Peach slices, best before 1987. Still smells faintly of peaches.' },

  { id: 'minnow', name: 'Sunny Minnow', rarity: 'common', price: 6, phases: ['golden', 'sunset'], diff: 1,
    size: [4, 9], len: 10, h: 5, pattern: 'none',
    body: '#ffb35c', belly: '#ffe6a8', fin: '#ff8a4c', accent: '#ff8a4c',
    blurb: 'Tiny, bright, and absolutely convinced it is a shark.' },
  { id: 'perch', name: 'Peach Perch', rarity: 'common', price: 9, phases: ALL_DAY, diff: 1.4,
    size: [10, 25], len: 13, h: 7, pattern: 'stripes',
    body: '#ffab8a', belly: '#fff0d8', fin: '#ff7a6a', accent: '#e0705a',
    blurb: 'Smells faintly of summer. Nobody knows why.' },
  { id: 'carp', name: 'Pebble Carp', rarity: 'common', price: 11, phases: ALL_DAY, diff: 1.5,
    size: [20, 45], len: 15, h: 8, pattern: 'spots',
    body: '#bf9f80', belly: '#ecdcc4', fin: '#8f6f5f', accent: '#7a5a4a',
    blurb: 'Collects shiny pebbles and will not be sharing them.' },
  { id: 'guppy', name: 'Dusk Guppy', rarity: 'common', price: 8, phases: ['dusk', 'night'], diff: 1.2,
    size: [3, 6], len: 9, h: 5, pattern: 'gradient',
    body: '#c8a8f0', belly: '#f0e0ff', fin: '#9a6ae8', accent: '#ff9ec4',
    blurb: 'Only comes out once the sky turns purple to match.' },
  { id: 'bream', name: 'Blushing Bream', rarity: 'common', price: 13, phases: ['sunset', 'dusk'], diff: 1.8,
    size: [15, 35], len: 12, h: 10, shape: 'round', pattern: 'none',
    body: '#ff9ec4', belly: '#ffe0ec', fin: '#e06a9a', accent: '#e06a9a',
    blurb: 'Gets flustered when you look at it. Please be gentle.' },

  { id: 'koi', name: 'Marmalade Koi', rarity: 'uncommon', price: 32, phases: ['golden', 'sunset'], diff: 2.4,
    size: [30, 70], len: 16, h: 8, pattern: 'patches',
    body: '#fff3e6', belly: '#fff8f0', fin: '#ffb86b', accent: '#ff7a3c',
    blurb: 'Every pattern is unique, like a sticky little fingerprint.' },
  { id: 'puffer', name: 'Cotton Candy Puffer', rarity: 'uncommon', price: 40, phases: ['sunset', 'dusk'], diff: 2.8,
    size: [10, 25], r: 5, shape: 'puffer', pattern: 'spots',
    body: '#ffc4e0', belly: '#fff4fa', fin: '#8fd1f0', accent: '#7fb8e6',
    blurb: 'Puffs up when startled. Sadly, does not taste like candy.' },
  { id: 'catfish', name: 'Honey Catfish', rarity: 'uncommon', price: 36, phases: ['dusk', 'night'], diff: 2.5,
    size: [30, 80], len: 18, h: 7, pattern: 'spots', whiskers: true,
    body: '#d9a05a', belly: '#f5e0b0', fin: '#a8703a', accent: '#8a5a2a',
    blurb: 'Those whiskers are for sensing snacks. Mostly snacks.' },
  { id: 'trout', name: 'Lantern Trout', rarity: 'uncommon', price: 38, phases: ['night'], diff: 2.9,
    size: [25, 50], len: 16, h: 7, pattern: 'spots',
    body: '#4a5a8a', belly: '#c0d0f0', fin: '#3a4070', accent: '#ffd27a',
    blurb: 'Its spots glow softly, like a string of fairy lights.' },

  { id: 'salmon', name: 'Rosé Salmon', rarity: 'rare', price: 95, phases: ['golden', 'sunset'], diff: 3.5,
    size: [50, 90], len: 18, h: 7, pattern: 'gradient',
    body: '#ff8a8a', belly: '#ffe0d0', fin: '#e0606a', accent: '#ffb07a',
    blurb: 'Swims upstream purely for the view.' },
  { id: 'eel', name: 'Ember Eel', rarity: 'rare', price: 110, phases: ['sunset', 'dusk'], diff: 4,
    size: [60, 120], len: 24, shape: 'eel', pattern: 'stripes',
    body: '#e0503a', belly: '#ffb05a', fin: '#ffd27a', accent: '#b83a2a',
    blurb: 'Warm to the touch. Keeps the pond cosy in winter.' },
  { id: 'sunfish', name: 'Starry Sunfish', rarity: 'rare', price: 130, phases: ['night'], diff: 4.2,
    size: [30, 60], len: 14, h: 12, shape: 'round', pattern: 'stars',
    body: '#2e2e70', belly: '#3e3e90', fin: '#6a5ab0', accent: '#fff3c4',
    blurb: 'Swallowed a little piece of the night sky and kept it.' },

  { id: 'goldfish', name: 'Golden Sunfish', rarity: 'legendary', price: 735, phases: ['golden'], diff: 5,
    size: [40, 80], len: 15, h: 12, shape: 'round', pattern: 'stars',
    body: '#ffd23f', belly: '#fff3a0', fin: '#ffa030', accent: '#ffffff',
    blurb: 'Said to appear only when the light is exactly right.' },
  { id: 'moonkoi', name: 'Moonbeam Koi', rarity: 'legendary', price: 840, phases: ['night'], diff: 5.3,
    size: [60, 100], len: 18, h: 9, pattern: 'patches',
    body: '#ece8ff', belly: '#ffffff', fin: '#b8a8f0', accent: '#9b86e0',
    blurb: 'Nobody has ever seen it blink. Nobody has ever seen it eat.' },
  { id: 'dragon', name: 'Twilight Dragonfish', rarity: 'legendary', price: 1050, phases: ['dusk'], diff: 5.8,
    size: [100, 200], len: 28, shape: 'eel', pattern: 'spots', whiskers: true,
    body: '#6a3a9a', belly: '#c07ae0', fin: '#ffd27a', accent: '#ffd27a',
    blurb: 'The old dock-keepers say it guards the last light of day.' },
  // ---- Lily Lagoon
  { id: 'loach', name: 'Lotus Loach', rarity: 'common', price: 14, phases: ALL_DAY, diff: 1.3, where: ['lagoon'],
    size: [8, 18], len: 18, shape: 'eel', pattern: 'spots',
    body: '#e8a0b8', belly: '#ffe0ea', fin: '#c87898', accent: '#b06080',
    blurb: 'Wiggles through lily roots looking for dropped petals.' },
  { id: 'mintminnow', name: 'Mint Minnow', rarity: 'common', price: 11, phases: ['golden', 'sunset'], diff: 1, where: ['lagoon'],
    size: [4, 10], len: 10, h: 5, pattern: 'none',
    body: '#8fe0b8', belly: '#e0fff0', fin: '#5fc098', accent: '#5fc098',
    blurb: 'Fresh! Cool! Tastes like toothpaste (allegedly).' },
  { id: 'betta', name: 'Petal Betta', rarity: 'common', price: 16, phases: ['sunset', 'dusk', 'night'], diff: 1.6, where: ['lagoon'],
    size: [5, 9], len: 11, h: 7, pattern: 'gradient',
    body: '#ff7aa8', belly: '#ffd0e0', fin: '#c060e0', accent: '#ffb0f0',
    blurb: 'Its fins look like a peony in full bloom.' },
  { id: 'pike', name: 'Mossback Pike', rarity: 'uncommon', price: 48, phases: ['dusk', 'night', 'golden'], diff: 2.8, where: ['lagoon'],
    size: [40, 90], len: 21, h: 6, pattern: 'stripes',
    body: '#7a9a5a', belly: '#e0e8b0', fin: '#5a7a3a', accent: '#4a6a3a',
    blurb: 'Hides under lily pads and pretends to be a log.' },
  { id: 'axolotl', name: 'Pearl Axolotl', rarity: 'rare', price: 150, phases: ['dusk', 'night'], diff: 3.8, where: ['lagoon'],
    size: [15, 30], map: 'axolotl',
    blurb: 'Smiles constantly. Nobody knows what it knows.' },
  { id: 'blossomkoi', name: 'Blossom Koi', rarity: 'legendary', price: 1140, phases: ['sunset'], diff: 5.4, where: ['lagoon'],
    size: [60, 110], len: 18, h: 9, pattern: 'patches',
    body: '#fff0f4', belly: '#ffffff', fin: '#ffb0c8', accent: '#ff6a9a',
    blurb: 'Petals drift up from the water wherever it has been.' },

  // ---- Coral Cove
  { id: 'clownfish', name: 'Candy Clownfish', rarity: 'common', price: 18, phases: ['golden', 'sunset', 'dusk'], diff: 1.5, where: ['cove'],
    size: [6, 12], len: 11, h: 7, pattern: 'stripes',
    body: '#ff8a3c', belly: '#ffb070', fin: '#e0602a', accent: '#fff4e0',
    blurb: 'Lives in an anemone and refuses to share the rent.' },
  { id: 'sardine', name: 'Sandy Sardine', rarity: 'common', price: 12, phases: ALL_DAY, diff: 1.2, where: ['cove'],
    size: [10, 20], len: 13, h: 5, pattern: 'gradient',
    body: '#b0c0d8', belly: '#f0f4ff', fin: '#8090b0', accent: '#e0b070',
    blurb: 'Travels in a crowd of ten thousand best friends.' },
  { id: 'crab', name: 'Peach Crab', rarity: 'uncommon', price: 55, phases: ['golden', 'sunset', 'dusk'], diff: 2.6, where: ['cove'],
    size: [8, 20], map: 'crab', bottom: true,
    blurb: 'Walks sideways out of stubbornness, not necessity.' },
  { id: 'jelly', name: 'Bubblegum Jelly', rarity: 'uncommon', price: 60, phases: ['dusk', 'night'], diff: 2.2, where: ['cove'],
    size: [10, 30], map: 'jelly',
    blurb: 'Mostly water. Mostly vibes.' },
  { id: 'grouper', name: 'Coral Grouper', rarity: 'rare', price: 170, phases: ['sunset', 'dusk'], diff: 4, where: ['cove'],
    size: [50, 100], len: 16, h: 12, shape: 'round', pattern: 'spots',
    body: '#ff7a6a', belly: '#ffd0b8', fin: '#e0506a', accent: '#fff0c0',
    blurb: 'Big, grumpy, and secretly very soft-hearted.' },
  { id: 'marlin', name: 'Sunset Marlin', rarity: 'legendary', price: 1400, phases: ['golden', 'sunset'], diff: 5.8, where: ['cove'],
    size: [150, 300], len: 24, h: 7, pattern: 'gradient', bill: true,
    body: '#4a5aa8', belly: '#ffd0a0', fin: '#ff8a5c', accent: '#ff9a5c',
    blurb: 'Its sail catches the last light like a tiny sunset of its own.' },

  // ---- Aurora Bay
  { id: 'cod', name: 'Snowcone Cod', rarity: 'common', price: 20, phases: ALL_DAY, diff: 1.6, where: ['bay'],
    size: [25, 50], len: 15, h: 8, pattern: 'spots',
    body: '#e8e4f0', belly: '#ffffff', fin: '#a8b8e0', accent: '#7fb8e6',
    blurb: 'Fluffy-looking. Actually just very cold.' },
  { id: 'smelt', name: 'Frost Smelt', rarity: 'common', price: 15, phases: ['dusk', 'night', 'golden'], diff: 1.3, where: ['bay'],
    size: [8, 15], len: 10, h: 4, pattern: 'gradient',
    body: '#c8b8ff', belly: '#f0ecff', fin: '#9a8ae0', accent: '#8fe0f0',
    blurb: 'Smells faintly of cucumbers and snowfall.' },
  { id: 'char', name: 'Blushing Char', rarity: 'uncommon', price: 65, phases: ['golden', 'sunset', 'dusk'], diff: 2.9, where: ['bay'],
    size: [30, 60], len: 16, h: 7, pattern: 'spots',
    body: '#6a7ab0', belly: '#ff9ab0', fin: '#e07090', accent: '#ffd0e0',
    blurb: 'Turns pinker the colder it gets. Very relatable.' },
  { id: 'auroraeel', name: 'Aurora Eel', rarity: 'rare', price: 190, phases: ['night', 'dusk'], diff: 4.3, where: ['bay'],
    size: [70, 140], len: 26, shape: 'eel', pattern: 'stripes',
    body: '#5ae0b0', belly: '#c0fff0', fin: '#c07aff', accent: '#9a6aff',
    blurb: 'Glows in soft ribbons, just like the sky above it.' },
  { id: 'narwhal', name: 'Tiny Narwhal', rarity: 'legendary', price: 1575, phases: ['night'], diff: 6, where: ['bay'],
    size: [80, 150], map: 'narwhal',
    blurb: 'A baby. Its horn is mostly for pointing at things it likes.' },
  { id: 'bottle', name: 'Message in a Bottle', rarity: 'junk', price: 25, phases: ALL_DAY, diff: 0.6, where: ['cove', 'bay', 'cloud'],
    size: [20, 25], map: 'bottle', bottom: true,
    blurb: 'It says: "If found, please go fishing more." Wise words.' },
  // ---- more Sunset Dock
  { id: 'darter', name: 'Dewdrop Darter', rarity: 'common', price: 8, phases: ['sunrise', 'day'], diff: 1.1,
    size: [3, 8], len: 9, h: 4, pattern: 'none',
    body: '#a8e0ff', belly: '#ffffff', fin: '#7ac0f0', accent: '#7ac0f0',
    blurb: 'Made mostly of morning dew and enthusiasm.' },
  { id: 'bluegill', name: 'Buttercup Bluegill', rarity: 'common', price: 12, phases: ['day', 'golden'], diff: 1.4,
    size: [10, 22], len: 11, h: 9, shape: 'round', pattern: 'stripes',
    body: '#ffd86a', belly: '#fff4c0', fin: '#7fb8e6', accent: '#e8b848',
    blurb: 'Hold it under your chin to see if you like butter.' },
  { id: 'rainbowtrout', name: 'Pastel Rainbow Trout', rarity: 'uncommon', price: 42, phases: ['sunrise', 'day'], diff: 2.6,
    size: [25, 55], len: 17, h: 7, pattern: 'gradient',
    body: '#8fd1e0', belly: '#fff4f8', fin: '#c79bf2', accent: '#ff9ec4',
    blurb: 'Someone left the rainbow in the wash with a pink sock.' },
  { id: 'grandpacarp', name: 'Grandpa Carp', rarity: 'rare', price: 140, phases: ['day', 'dusk'], diff: 3.6,
    size: [60, 110], len: 20, h: 10, pattern: 'spots', whiskers: true,
    body: '#a08060', belly: '#e8d8b8', fin: '#7a5a40', accent: '#6a4a30',
    blurb: 'Has lived in this pond for 80 years. Tells the same three stories.' },

  // ---- more Lily Lagoon
  { id: 'danio', name: 'Dragonfly Danio', rarity: 'common', price: 11, phases: ['sunrise', 'day'], diff: 1.2, where: ['lagoon'],
    size: [3, 7], len: 10, h: 4, pattern: 'stripes',
    body: '#7fd0f0', belly: '#e8f8ff', fin: '#4a8ad0', accent: '#4a8ad0',
    blurb: 'Zips around like it has somewhere very important to be.' },
  { id: 'gourami', name: 'Rosy Gourami', rarity: 'common', price: 15, phases: ['day', 'golden', 'sunset'], diff: 1.5, where: ['lagoon'],
    size: [8, 14], len: 12, h: 8, pattern: 'gradient',
    body: '#ffb0a0', belly: '#fff0ea', fin: '#ff7aa0', accent: '#ff7aa0',
    blurb: 'Blows little bubble nests and is very proud of them.' },
  { id: 'mudskipper', name: 'Mossy Mudskipper', rarity: 'uncommon', price: 44, phases: ALL_DAY, diff: 2.4, where: ['lagoon'],
    size: [10, 20], len: 16, shape: 'eel', pattern: 'spots',
    body: '#8a9a60', belly: '#d8e0b0', fin: '#6a7a40', accent: '#5a6a30',
    blurb: 'Half fish, half frog, fully confused about which.' },
  { id: 'sturgeon', name: 'Sunrise Sturgeon', rarity: 'rare', price: 160, phases: ['sunrise'], diff: 3.9, where: ['lagoon'],
    size: [90, 180], len: 24, h: 6, pattern: 'stripes',
    body: '#b8a0c8', belly: '#f0e8f8', fin: '#8a70a8', accent: '#9a80b8',
    blurb: 'Older than the dinosaurs. Still an early riser.' },

  // ---- more Coral Cove
  { id: 'tang', name: 'Tang Tang', rarity: 'common', price: 17, phases: ['day', 'golden'], diff: 1.5, where: ['cove'],
    size: [10, 25], len: 12, h: 9, shape: 'round', pattern: 'none',
    body: '#4a80e0', belly: '#6aa0f0', fin: '#ffd23f', accent: '#2a4aa0',
    blurb: 'Forgets things constantly. Very good at swimming, though.' },
  { id: 'parrotfish', name: 'Parrotfish Pop', rarity: 'common', price: 19, phases: ['sunrise', 'day', 'golden'], diff: 1.7, where: ['cove'],
    size: [20, 50], len: 14, h: 8, pattern: 'gradient',
    body: '#5ad0a0', belly: '#d0fff0', fin: '#ff8ab0', accent: '#ff8ab0',
    blurb: 'Chews coral and poops sand. That beach? Thank a parrotfish.' },
  { id: 'seahorse', name: 'Sea Pony', rarity: 'uncommon', price: 58, phases: ['sunrise', 'day', 'dusk'], diff: 2.3, where: ['cove'],
    size: [8, 18], map: 'seahorse',
    blurb: 'The dad carries the babies. Absolute legend.' },
  { id: 'octopus', name: 'Octo Pal', rarity: 'rare', price: 150, phases: ['dusk', 'night', 'day'], diff: 3.8, where: ['cove'],
    size: [30, 80], map: 'octopus',
    blurb: 'Has opened your tackle box twice already. Very clever. Very sneaky.' },

  // ---- more Aurora Bay
  { id: 'herring', name: 'Icicle Herring', rarity: 'common', price: 16, phases: ['day', 'sunrise', 'golden'], diff: 1.3, where: ['bay'],
    size: [15, 30], len: 12, h: 5, pattern: 'gradient',
    body: '#d0e8ff', belly: '#ffffff', fin: '#a0c0e8', accent: '#8ab0e0',
    blurb: 'So shiny you can see your own reflection in it.' },
  { id: 'flounder', name: 'Frosted Flounder', rarity: 'common', price: 18, phases: ['sunrise', 'day', 'sunset'], diff: 1.6, where: ['bay'],
    size: [20, 45], len: 14, h: 9, shape: 'round', pattern: 'spots',
    body: '#c8b8a0', belly: '#f0e8dc', fin: '#a89880', accent: '#8a7860',
    blurb: 'Both eyes on one side. It has made peace with this.' },
  { id: 'snowcrab', name: 'Snow Crab', rarity: 'uncommon', price: 62, phases: ALL_DAY, diff: 2.5, where: ['bay'],
    size: [10, 25], map: 'crab', bottom: true, pal: { p: '#f0e8ff', h: '#ffffff', l: '#b0b8e0', k: OUTLINE },
    blurb: 'Wears its own little snowsuit, all year round.' },
  { id: 'glaciersalmon', name: 'Glacier Salmon', rarity: 'rare', price: 175, phases: ['sunrise', 'day'], diff: 4, where: ['bay'],
    size: [50, 100], len: 18, h: 7, pattern: 'gradient',
    body: '#a8c0ff', belly: '#fff0f4', fin: '#8098e0', accent: '#ff9ab0',
    blurb: 'Swam here from a glacier. Refuses to talk about the journey.' },

  // ---- Blossom River
  { id: 'sakuraminnow', name: 'Sakura Minnow', rarity: 'common', price: 20, phases: ['sunrise', 'day', 'golden', 'sunset'], diff: 1.3, where: ['blossom'],
    size: [4, 9], len: 9, h: 5, pattern: 'none',
    body: '#ffc0d8', belly: '#fff4f8', fin: '#ff90b8', accent: '#ff90b8',
    blurb: 'Hides among fallen petals. You will never find it. Oh wait, there it is.' },
  { id: 'mochicarp', name: 'Mochi Carp', rarity: 'common', price: 24, phases: ALL_DAY, diff: 1.6, where: ['blossom'],
    size: [15, 30], len: 13, h: 10, shape: 'round', pattern: 'patches',
    body: '#fff4f0', belly: '#ffffff', fin: '#ffc0d0', accent: '#ffb0c8',
    blurb: 'Soft, round, squishy. Please do not eat it.' },
  { id: 'matchaloach', name: 'Matcha Loach', rarity: 'common', price: 22, phases: ['day', 'dusk', 'night'], diff: 1.5, where: ['blossom'],
    size: [10, 20], len: 17, shape: 'eel', pattern: 'spots',
    body: '#9ac878', belly: '#e0f0c8', fin: '#6a9a50', accent: '#6a9a50',
    blurb: 'Slightly bitter. Very calming. Best enjoyed slowly.' },
  { id: 'lanterngold', name: 'Lantern Goldfish', rarity: 'uncommon', price: 70, phases: ['dusk', 'night'], diff: 2.6, where: ['blossom'],
    size: [8, 16], len: 12, h: 9, shape: 'round', pattern: 'gradient',
    body: '#ff7a3c', belly: '#ffe0a0', fin: '#ffd27a', accent: '#ffd23f',
    blurb: 'Glows like a paper lantern at the festival.' },
  { id: 'teakoi', name: 'Hojicha Koi', rarity: 'uncommon', price: 75, phases: ['sunrise', 'day', 'golden'], diff: 2.8, where: ['blossom'],
    size: [30, 70], len: 16, h: 8, pattern: 'patches',
    body: '#fff0dc', belly: '#fff8f0', fin: '#c09070', accent: '#8a5a3a',
    blurb: 'Roasted-tea brown and milky white. Pairs well with a nap.' },
  { id: 'cranefish', name: 'Paper Crane Fish', rarity: 'rare', price: 200, phases: ['day', 'sunset'], diff: 4.1, where: ['blossom'],
    size: [20, 40], len: 15, h: 6, pattern: 'stripes',
    body: '#f4efe6', belly: '#ffffff', fin: '#e0566e', accent: '#e0566e',
    blurb: 'Folded itself out of a wish somebody made at the river.' },
  { id: 'spiritkoi', name: 'Spirit Koi', rarity: 'legendary', price: 1660, phases: ['night'], diff: 5.9, where: ['blossom'],
    size: [70, 120], len: 20, h: 9, pattern: 'stars',
    body: '#b8f0ff', belly: '#e8fcff', fin: '#88d8ff', accent: '#ffffff',
    blurb: 'You can see the moon through it. It is almost certainly a ghost.' },

  // ---- Ember Isle
  { id: 'cinderminnow', name: 'Cinder Minnow', rarity: 'common', price: 22, phases: ALL_DAY, diff: 1.5, where: ['ember'],
    size: [4, 10], len: 9, h: 5, pattern: 'spots',
    body: '#4a3a4a', belly: '#7a6070', fin: '#ff7a3c', accent: '#ff7a3c',
    blurb: 'Glows a little when it is happy. Always a little warm.' },
  { id: 'magmamolly', name: 'Magma Molly', rarity: 'common', price: 26, phases: ['day', 'golden', 'sunset', 'dusk'], diff: 1.7, where: ['ember'],
    size: [5, 12], len: 11, h: 8, shape: 'round', pattern: 'gradient',
    body: '#ff5a3a', belly: '#ffc070', fin: '#ffd23f', accent: '#ffd23f',
    blurb: 'Do not hold for too long. Oven mitts recommended.' },
  { id: 'obsidianeel', name: 'Obsidian Eel', rarity: 'uncommon', price: 80, phases: ['dusk', 'night', 'sunrise'], diff: 2.9, where: ['ember'],
    size: [50, 100], len: 22, shape: 'eel', pattern: 'stripes',
    body: '#2a2238', belly: '#5a4a68', fin: '#ff7a3c', accent: '#ff5a3a',
    blurb: 'Glossy, black, and dramatic. Probably writes poetry.' },
  { id: 'ashpuffer', name: 'Ash Puffer', rarity: 'uncommon', price: 78, phases: ['day', 'golden', 'sunset'], diff: 2.7, where: ['ember'],
    size: [10, 25], r: 5, shape: 'puffer', pattern: 'spots',
    body: '#8a8090', belly: '#c8c0d0', fin: '#ff7a3c', accent: '#ff5a3a',
    blurb: 'Puffs up in a little cloud of smoke. Very theatrical.' },
  { id: 'lavacrab', name: 'Lava Crab', rarity: 'rare', price: 220, phases: ALL_DAY, diff: 4, where: ['ember'],
    size: [15, 35], map: 'crab', bottom: true, pal: { p: '#ff5a3a', h: '#ffd23f', l: '#b8302a', k: OUTLINE },
    blurb: 'Its shell is still cooling. Please wait five business days.' },
  { id: 'phoenix', name: 'Phoenix Fin', rarity: 'legendary', price: 1925, phases: ['sunset', 'dusk'], diff: 6, where: ['ember'],
    size: [80, 150], len: 22, h: 9, pattern: 'gradient', bill: false,
    body: '#ff3a3a', belly: '#ffd080', fin: '#ffec80', accent: '#ffd23f',
    blurb: 'Every sunset it bursts into sparks and swims out of its own ashes.' },

  // ---- Cloud Lake
  { id: 'cloudguppy', name: 'Cloud Guppy', rarity: 'common', price: 26, phases: ALL_DAY, diff: 1.5, where: ['cloud'],
    size: [3, 7], len: 9, h: 5, pattern: 'none',
    body: '#ffffff', belly: '#e8f0ff', fin: '#b8d0ff', accent: '#b8d0ff',
    blurb: 'Fluffy. Weightless. Occasionally rains a little.' },
  { id: 'skysardine', name: 'Sky Sardine', rarity: 'common', price: 24, phases: ['sunrise', 'day', 'golden'], diff: 1.4, where: ['cloud'],
    size: [10, 20], len: 12, h: 4, pattern: 'gradient',
    body: '#8fc8ff', belly: '#ffffff', fin: '#6aa8e8', accent: '#ffffff',
    blurb: 'Swims in flocks shaped like birds, just to mess with the birds.' },
  { id: 'rainbowtetra', name: 'Rainbow Tetra', rarity: 'common', price: 28, phases: ['sunrise', 'day', 'sunset'], diff: 1.6, where: ['cloud'],
    size: [3, 6], len: 10, h: 5, pattern: 'stripes',
    body: '#ff9ec4', belly: '#fff4f8', fin: '#8fe0f0', accent: '#8fe0f0',
    blurb: 'Appears right after it rains. Collect all seven colours.' },
  { id: 'balloonpuffer', name: 'Balloon Puffer', rarity: 'uncommon', price: 85, phases: ['day', 'golden', 'dusk'], diff: 2.8, where: ['cloud'],
    size: [10, 30], r: 6, shape: 'puffer', pattern: 'spots',
    body: '#ffd0e0', belly: '#ffffff', fin: '#ffffff', accent: '#ff9ec4',
    blurb: 'Filled with helium. Hold on tight or it floats away.' },
  { id: 'thundertuna', name: 'Thunder Tuna', rarity: 'rare', price: 230, phases: ['day', 'sunset'], diff: 4.3, where: ['cloud'],
    size: [80, 160], len: 20, h: 9, pattern: 'stripes',
    body: '#5a6ab0', belly: '#e0e8ff', fin: '#ffd23f', accent: '#ffd23f',
    blurb: 'Fast as lightning, loud as thunder. Not great at hide and seek.' },
  { id: 'cometeel', name: 'Comet Eel', rarity: 'rare', price: 240, phases: ['night', 'dusk'], diff: 4.4, where: ['cloud'],
    size: [60, 130], len: 26, shape: 'eel', pattern: 'spots',
    body: '#3a3a8a', belly: '#6a6ab8', fin: '#fff3c4', accent: '#fff3c4',
    blurb: 'Leaves a sparkly tail behind it. Make a wish!' },
  { id: 'cloudwhale', name: 'Cloud Whale', rarity: 'legendary', price: 2275, phases: ['sunrise', 'day'], diff: 6, where: ['cloud'],
    size: [300, 600], map: 'whale',
    blurb: 'Sings a very low song that makes the clouds drift. It is a baby.' },

  // ---- ???
  // ---------------------------------------------------- 100 more fish --
  // Fifteen or so per spot, themed to where they live.
  // Sunset Dock
  { id: 'freckledace', name: 'Freckled Dace', rarity: 'common', price: 7, phases: ['sunrise', 'day'], diff: 1.1,
    size: [5, 10], len: 10, h: 5, pattern: 'spots',
    body: '#e8b88a', belly: '#fff0dc', fin: '#c88a5a', accent: '#a0603a',
    blurb: 'Covered in freckles from too much sunbathing.' },
  { id: 'marshmallowshiner', name: 'Marshmallow Shiner', rarity: 'common', price: 8, phases: ['day', 'golden'], diff: 1.2,
    size: [6, 12], len: 11, h: 5, pattern: 'none',
    body: '#fff0f4', belly: '#ffffff', fin: '#ffc8d8', accent: '#ffc8d8',
    blurb: 'Soft, squishy, and slightly toasted on one side.' },
  { id: 'cattailchub', name: 'Cattail Chub', rarity: 'common', price: 10, phases: ALL_DAY, diff: 1.4,
    size: [12, 28], len: 13, h: 7, pattern: 'stripes',
    body: '#a8905a', belly: '#f0e4c0', fin: '#7a6a3a', accent: '#6a5a2a',
    blurb: 'Hides in the reeds and pretends to be one.' },
  { id: 'lamplightloach', name: 'Lamplight Loach', rarity: 'common', price: 11, phases: ['dusk', 'night'], diff: 1.5,
    size: [8, 16], len: 16, shape: 'eel', pattern: 'spots',
    body: '#d8a860', belly: '#fff0c0', fin: '#ffd27a', accent: '#8a6a3a',
    blurb: 'Glows just enough to read a very small book by.' },
  { id: 'pumpkinseedpip', name: 'Pumpkinseed Pip', rarity: 'common', price: 9, phases: ['golden', 'sunset'], diff: 1.3,
    size: [6, 14], len: 11, h: 9, shape: 'round', pattern: 'spots',
    body: '#ff9a50', belly: '#ffe0b0', fin: '#e07030', accent: '#5a8a50',
    blurb: 'Round, orange, and extremely autumnal.' },
  { id: 'dozybullhead', name: 'Dozy Bullhead', rarity: 'common', price: 12, phases: ['night', 'sunrise'], diff: 1.6,
    size: [15, 30], len: 13, h: 7, pattern: 'none', whiskers: true,
    body: '#8a7a6a', belly: '#d8ccb8', fin: '#6a5a4a', accent: '#4a3a2a',
    blurb: 'Sleeps through most of its own life. Relatable.' },
  { id: 'peachgar', name: 'Peach Gar', rarity: 'uncommon', price: 45, phases: ['sunset'], diff: 2.5,
    size: [50, 100], len: 20, h: 5, pattern: 'stripes', bill: true,
    body: '#ffb090', belly: '#fff0e0', fin: '#e08060', accent: '#c06040',
    blurb: 'All nose. Very proud of it.' },
  { id: 'lanternbass', name: 'Lantern Bass', rarity: 'uncommon', price: 42, phases: ['dusk', 'night'], diff: 2.6,
    size: [30, 55], len: 16, h: 9, pattern: 'patches',
    body: '#5a6a4a', belly: '#d0d8b0', fin: '#3a4a2a', accent: '#ffd27a',
    blurb: 'Its patches glow when it is thinking very hard.' },
  { id: 'sundaecrappie', name: 'Sundae Crappie', rarity: 'uncommon', price: 38, phases: ['day', 'golden'], diff: 2.3,
    size: [20, 35], len: 13, h: 10, shape: 'round', pattern: 'spots',
    body: '#fff4e0', belly: '#ffffff', fin: '#ff9ec4', accent: '#a05a3a',
    blurb: 'Vanilla with chocolate sprinkles. Do not lick.' },
  { id: 'fireflyeel', name: 'Firefly Eel', rarity: 'uncommon', price: 55, phases: ['night'], diff: 2.8,
    size: [40, 80], len: 22, shape: 'eel', pattern: 'stars',
    body: '#3a3a5a', belly: '#8a8ab0', fin: '#ffd27a', accent: '#fff3a0',
    blurb: 'Borrowed its lights from the fireflies. Never gave them back.' },
  { id: 'violetmuskie', name: 'Violet Muskie', rarity: 'rare', price: 140, phases: ['dusk'], diff: 4.0,
    size: [80, 140], len: 20, h: 8, pattern: 'stripes',
    body: '#8a6ab0', belly: '#e0d0f0', fin: '#5a4a8a', accent: '#4a3a70',
    blurb: 'The lake\'s quiet queen. Everyone moves out of her way.' },
  { id: 'beaconpike', name: 'Beacon Pike', rarity: 'rare', price: 125, phases: ['night', 'sunrise'], diff: 3.8,
    size: [60, 110], len: 19, h: 7, pattern: 'gradient',
    body: '#e0e8f0', belly: '#ffffff', fin: '#ff6a5a', accent: '#ff6a5a',
    blurb: 'Swims circles around the lighthouse, keeping watch.' },
  { id: 'honeycarp', name: 'Honeycomb Carp', rarity: 'rare', price: 110, phases: ['golden'], diff: 3.6,
    size: [40, 70], len: 16, h: 9, pattern: 'patches',
    body: '#ffc040', belly: '#fff0b0', fin: '#e09020', accent: '#c07010',
    blurb: 'Sticky, sweet, and followed by exactly one confused bee.' },
  { id: 'ladylake', name: 'Lady of the Lake', rarity: 'legendary', price: 1225, phases: ['sunset'], diff: 5.6,
    size: [150, 260], len: 24, h: 9, pattern: 'gradient',
    body: '#ffb0c8', belly: '#fff0f4', fin: '#ffd27a', accent: '#ff7a5a',
    blurb: 'Rises every sunset to check the sky is still pretty. It always is.' },
  { id: 'stardustgar', name: 'Stardust Gar', rarity: 'legendary', price: 910, phases: ['night'], diff: 5.2,
    size: [100, 180], len: 22, h: 6, pattern: 'stars', bill: true,
    body: '#2a2a5a', belly: '#6a6aa0', fin: '#b89cff', accent: '#ffffff',
    blurb: 'A little piece of night sky that fell into the lake.' },
  // Lily Lagoon
  { id: 'lilypadlurker', name: 'Lilypad Lurker', rarity: 'common', price: 12, phases: ALL_DAY, diff: 1.3, where: ['lagoon'],
    size: [8, 18], len: 12, h: 9, shape: 'round', pattern: 'spots',
    body: '#7ac070', belly: '#e0f0c0', fin: '#4a8a44', accent: '#ff9ec4',
    blurb: 'Wears a lily pad as a hat. Fooling no one.' },
  { id: 'petalpleco', name: 'Petal Pleco', rarity: 'common', price: 14, phases: ['day', 'golden'], diff: 1.5, where: ['lagoon'],
    size: [10, 20], len: 13, h: 6, pattern: 'spots', whiskers: true,
    body: '#c8a0a0', belly: '#f0e0e0', fin: '#a07070', accent: '#ff9ec4',
    blurb: 'Tidies the lagoon floor one petal at a time.' },
  { id: 'teacuptetra', name: 'Teacup Tetra', rarity: 'common', price: 11, phases: ['sunrise', 'day'], diff: 1.1, where: ['lagoon'],
    size: [3, 6], len: 9, h: 5, pattern: 'stripes',
    body: '#ffd0e0', belly: '#ffffff', fin: '#ff8ab0', accent: '#7fb8e6',
    blurb: 'Small enough to fit in a teacup. Please don\'t check.' },
  { id: 'froggygoby', name: 'Froggy Goby', rarity: 'common', price: 13, phases: ['dusk', 'night'], diff: 1.4, where: ['lagoon'],
    size: [5, 12], len: 11, h: 8, shape: 'round', pattern: 'spots',
    body: '#8fd18f', belly: '#f0fff0', fin: '#5aa060', accent: '#3a7a44',
    blurb: 'Thinks it is a frog. Tries to hop. Cannot hop.' },
  { id: 'mistyrasbora', name: 'Misty Rasbora', rarity: 'common', price: 12, phases: ['sunrise', 'dusk'], diff: 1.2, where: ['lagoon'],
    size: [3, 7], len: 10, h: 5, pattern: 'gradient',
    body: '#e0d0f0', belly: '#fff8ff', fin: '#b8a0d8', accent: '#ff9ec4',
    blurb: 'Only visible in the mist, like a secret.' },
  { id: 'willowwhiptail', name: 'Willow Whiptail', rarity: 'common', price: 16, phases: ['golden', 'sunset'], diff: 1.7, where: ['lagoon'],
    size: [15, 30], len: 18, shape: 'eel', pattern: 'stripes',
    body: '#a8c890', belly: '#f0f8e0', fin: '#7aa060', accent: '#5a8040',
    blurb: 'Sways like the willow branches above it.' },
  { id: 'rosequartzkoi', name: 'Rose Quartz Koi', rarity: 'uncommon', price: 60, phases: ['sunset', 'dusk'], diff: 2.6, where: ['lagoon'],
    size: [35, 70], len: 16, h: 8, pattern: 'patches',
    body: '#ffe8f0', belly: '#fffafc', fin: '#ffb0cc', accent: '#ff7aa8',
    blurb: 'Polished by a thousand years of gentle water.' },
  { id: 'lotusgourami', name: 'Lotus Gourami', rarity: 'uncommon', price: 48, phases: ['day'], diff: 2.3, where: ['lagoon'],
    size: [10, 20], len: 12, h: 10, shape: 'round', pattern: 'gradient',
    body: '#ffc0d8', belly: '#fff0f6', fin: '#e080a8', accent: '#ffd27a',
    blurb: 'Blooms a little brighter at noon.' },
  { id: 'bobapuffer', name: 'Boba Puffer', rarity: 'uncommon', price: 52, phases: ['golden', 'sunset'], diff: 2.5, where: ['lagoon'],
    size: [8, 18], r: 5, shape: 'puffer', pattern: 'spots',
    body: '#e8d0b0', belly: '#fff4e0', fin: '#a07050', accent: '#4a3028',
    blurb: 'Full of tapioca pearls. Probably.' },
  { id: 'lavaxolotl', name: 'Lavender Axolotl', rarity: 'uncommon', price: 70, phases: ['night'], diff: 2.8, where: ['lagoon'],
    size: [15, 28], map: 'axolotl', bottom: true, pal: { g: '#b89cff', a: '#e8dcff', k: OUTLINE, m: '#9a7ae0', t: '#d8c8ff' },
    blurb: 'Smiles at everything. Especially you.' },
  { id: 'mirrorcarp', name: 'Mirror Carp', rarity: 'rare', price: 150, phases: ['sunrise'], diff: 3.8, where: ['lagoon'],
    size: [50, 90], len: 17, h: 9, pattern: 'patches',
    body: '#e0e8f0', belly: '#ffffff', fin: '#b0c0d0', accent: '#ffd27a',
    blurb: 'You can see your reflection in its scales. You look great.' },
  { id: 'fairybetta', name: 'Fairy Betta', rarity: 'rare', price: 170, phases: ['dusk'], diff: 4.1, where: ['lagoon'],
    size: [5, 9], len: 12, h: 9, pattern: 'gradient',
    body: '#c89cff', belly: '#f8f0ff', fin: '#ff9ed8', accent: '#7fe0e0',
    blurb: 'Its fins trail sparkles that fade before you can catch them.' },
  { id: 'wisteriaeel', name: 'Wisteria Eel', rarity: 'rare', price: 160, phases: ['night', 'dusk'], diff: 4.2, where: ['lagoon'],
    size: [70, 130], len: 24, shape: 'eel', pattern: 'spots',
    body: '#9a7ae0', belly: '#e0d0ff', fin: '#c8a8ff', accent: '#6a4ab0',
    blurb: 'Hangs from the lily stems like a bunch of flowers.' },
  { id: 'lilyempress', name: 'Lily Empress', rarity: 'legendary', price: 1365, phases: ['golden'], diff: 5.5, where: ['lagoon'],
    size: [120, 200], len: 22, h: 10, pattern: 'gradient',
    body: '#ffffff', belly: '#fff8fc', fin: '#ff9ec4', accent: '#7ac070',
    blurb: 'Every lily pad in the lagoon bows as she passes.' },
  { id: 'daydreamkoi', name: 'Daydream Koi', rarity: 'legendary', price: 1085, phases: ['day'], diff: 5.1, where: ['lagoon'],
    size: [60, 110], len: 18, h: 9, pattern: 'patches',
    body: '#b8e0ff', belly: '#ffffff', fin: '#ffb0cc', accent: '#fff3a0',
    blurb: 'Only appears if you stop trying so hard. Which is hard.' },
  // Coral Cove
  { id: 'sherbetwrasse', name: 'Sherbet Wrasse', rarity: 'common', price: 15, phases: ['day', 'golden'], diff: 1.3, where: ['cove'],
    size: [8, 18], len: 12, h: 6, pattern: 'stripes',
    body: '#ffb070', belly: '#fff0d0', fin: '#ff7a9a', accent: '#7ad0c0',
    blurb: 'Tastes like the rainbow. Is the rainbow.' },
  { id: 'sandydab', name: 'Sandy Dab', rarity: 'common', price: 13, phases: ALL_DAY, diff: 1.2, where: ['cove'],
    size: [10, 22], len: 14, h: 6, pattern: 'spots', bottom: true,
    body: '#e0c898', belly: '#f8ecd0', fin: '#b89a68', accent: '#8a7048',
    blurb: 'Lies flat and hopes you mistake it for sand. You did.' },
  { id: 'coconutgoby', name: 'Coconut Goby', rarity: 'common', price: 16, phases: ['sunrise', 'day'], diff: 1.4, where: ['cove'],
    size: [5, 10], len: 10, h: 8, shape: 'round', pattern: 'patches',
    body: '#8a5a3a', belly: '#fff8f0', fin: '#6a3a2a', accent: '#fff8f0',
    blurb: 'Lives inside half a coconut. It\'s a lovely apartment.' },
  { id: 'limechromis', name: 'Key Lime Chromis', rarity: 'common', price: 14, phases: ['golden', 'sunset'], diff: 1.3, where: ['cove'],
    size: [5, 10], len: 10, h: 6, pattern: 'none',
    body: '#b8f070', belly: '#f0ffd0', fin: '#80c040', accent: '#80c040',
    blurb: 'Zesty. Keeps the cove smelling fresh.' },
  { id: 'hermitcrab', name: 'Hermit Crab', rarity: 'common', price: 18, phases: ['dusk', 'night'], diff: 1.6, where: ['cove'],
    size: [5, 12], map: 'crab', bottom: true, pal: { p: '#ffb0a0', h: '#fff0e0', l: '#9a7ae0', k: OUTLINE },
    blurb: 'Moves house every week. Very picky about shells.' },
  { id: 'tidepoolblenny', name: 'Tidepool Blenny', rarity: 'common', price: 17, phases: ['sunrise', 'sunset'], diff: 1.5, where: ['cove'],
    size: [6, 12], len: 11, h: 6, pattern: 'spots', whiskers: true,
    body: '#c8a060', belly: '#f0e0b0', fin: '#a07040', accent: '#ff7a5a',
    blurb: 'Nosy. Knows everyone\'s business in the tide pools.' },
  { id: 'pastelangel', name: 'Pastel Angelfish', rarity: 'uncommon', price: 62, phases: ['day'], diff: 2.4, where: ['cove'],
    size: [12, 25], len: 12, h: 12, shape: 'round', pattern: 'stripes',
    body: '#fff0a0', belly: '#ffffff', fin: '#7ad0e0', accent: '#7ad0e0',
    blurb: 'Very elegant. Refuses to be photographed from the left.' },
  { id: 'picassotrigger', name: 'Picasso Trigger', rarity: 'uncommon', price: 58, phases: ['golden', 'sunset'], diff: 2.6, where: ['cove'],
    size: [20, 30], len: 13, h: 10, shape: 'round', pattern: 'stripes',
    body: '#f0e0c0', belly: '#fff8e8', fin: '#ffb040', accent: '#3a5a8a',
    blurb: 'A swimming art project. It knows.' },
  { id: 'moonjelly', name: 'Moon Jelly', rarity: 'uncommon', price: 66, phases: ['night'], diff: 2.2, where: ['cove'],
    size: [15, 30], map: 'jelly', pal: { j: '#d8f0ff', h: '#ffffff', k: OUTLINE, m: '#9ac0e8', l: '#b8d8f0', t: '#e8f8ff' },
    blurb: 'Glows like a nightlight. Mostly made of vibes.' },
  { id: 'butterflyfish', name: 'Butterfly Fish', rarity: 'uncommon', price: 55, phases: ['sunrise', 'day'], diff: 2.3, where: ['cove'],
    size: [10, 18], len: 11, h: 11, shape: 'round', pattern: 'spots',
    body: '#ffe070', belly: '#fffbe0', fin: '#3a3a5a', accent: '#3a3a5a',
    blurb: 'Flutters more than it swims.' },
  { id: 'lionfish', name: 'Frilly Lionfish', rarity: 'rare', price: 190, phases: ['dusk'], diff: 4.2, where: ['cove'],
    size: [25, 40], len: 14, h: 10, pattern: 'stripes',
    body: '#ff8a6a', belly: '#fff0e8', fin: '#ffd0c0', accent: '#b8302a',
    blurb: 'Dramatic fins, dramatic entrance, dramatic personality.' },
  { id: 'coralseahorse', name: 'Coral Seahorse', rarity: 'rare', price: 175, phases: ['golden'], diff: 3.8, where: ['cove'],
    size: [10, 20], map: 'seahorse', pal: { s: '#ff7aa0', b: '#ffd0e0', f: '#ffb0cc', e: OUTLINE },
    blurb: 'Holds onto the coral with its tail and refuses to let go.' },
  { id: 'humphead', name: 'Humphead Wrasse', rarity: 'rare', price: 210, phases: ['day', 'sunrise'], diff: 4.3, where: ['cove'],
    size: [100, 180], len: 16, h: 12, shape: 'round', pattern: 'patches',
    body: '#5ac0b0', belly: '#d0f8f0', fin: '#3a9a8a', accent: '#2a7a6a',
    blurb: 'Big forehead, big brain, big heart.' },
  { id: 'coraldragon', name: 'Coral Dragon', rarity: 'legendary', price: 1660, phases: ['sunset', 'dusk'], diff: 5.8, where: ['cove'],
    size: [140, 240], len: 28, shape: 'eel', pattern: 'spots', whiskers: true,
    body: '#ff8aa0', belly: '#ffe0e8', fin: '#ffd27a', accent: '#7ad0c0',
    blurb: 'Guards the reef. Also naps on it. Mostly naps.' },
  // Aurora Bay
  { id: 'icecubeguppy', name: 'Ice Cube Guppy', rarity: 'common', price: 16, phases: ALL_DAY, diff: 1.2, where: ['bay'],
    size: [3, 6], len: 9, h: 5, pattern: 'none',
    body: '#d8f0ff', belly: '#ffffff', fin: '#a0d0f0', accent: '#a0d0f0',
    blurb: 'Keeps your drink cold. Please don\'t put it in your drink.' },
  { id: 'slushsculpin', name: 'Slushie Sculpin', rarity: 'common', price: 18, phases: ['day', 'golden'], diff: 1.5, where: ['bay'],
    size: [8, 18], len: 12, h: 7, pattern: 'spots',
    body: '#a0b8e0', belly: '#e8f0ff', fin: '#7a90c0', accent: '#ff9ec4',
    blurb: 'Blue raspberry flavour. Allegedly.' },
  { id: 'mittencapelin', name: 'Mitten Capelin', rarity: 'common', price: 17, phases: ['sunrise', 'day'], diff: 1.3, where: ['bay'],
    size: [8, 15], len: 11, h: 5, pattern: 'stripes',
    body: '#8aa0c0', belly: '#f0f4ff', fin: '#e0566e', accent: '#e0566e',
    blurb: 'Knitted its own fins. They\'re a bit lumpy.' },
  { id: 'polarpollock', name: 'Polar Pollock', rarity: 'common', price: 20, phases: ['dusk', 'night'], diff: 1.6, where: ['bay'],
    size: [25, 50], len: 14, h: 7, pattern: 'gradient',
    body: '#6a80a8', belly: '#e8f0ff', fin: '#4a6090', accent: '#b0c8f0',
    blurb: 'Stays warm by thinking about soup.' },
  { id: 'snowballpuffer', name: 'Snowball Puffer', rarity: 'common', price: 22, phases: ['day'], diff: 1.7, where: ['bay'],
    size: [6, 14], r: 4, shape: 'puffer', pattern: 'spots',
    body: '#f8fbff', belly: '#ffffff', fin: '#c0d8f0', accent: '#a0c0e0',
    blurb: 'Please do not throw.' },
  { id: 'frostfry', name: 'Frost Fry', rarity: 'common', price: 15, phases: ['sunrise', 'night'], diff: 1.1, where: ['bay'],
    size: [2, 5], len: 9, h: 4, pattern: 'stars',
    body: '#c0e0ff', belly: '#ffffff', fin: '#8ac0f0', accent: '#ffffff',
    blurb: 'Hatched from a snowflake. Or so it says.' },
  { id: 'auroratetra', name: 'Aurora Tetra', rarity: 'uncommon', price: 58, phases: ['night'], diff: 2.5, where: ['bay'],
    size: [4, 8], len: 10, h: 6, pattern: 'gradient',
    body: '#7ae0c0', belly: '#e0fff4', fin: '#b89cff', accent: '#ff9ed8',
    blurb: 'Carries a tiny piece of the northern lights around.' },
  { id: 'walruswrasse', name: 'Walrus Wrasse', rarity: 'uncommon', price: 64, phases: ['day', 'golden'], diff: 2.6, where: ['bay'],
    size: [30, 55], len: 15, h: 9, pattern: 'none', whiskers: true,
    body: '#a88a78', belly: '#e8d8c8', fin: '#806050', accent: '#fff8f0',
    blurb: 'Has a magnificent moustache and knows it.' },
  { id: 'crystaljelly', name: 'Crystal Jelly', rarity: 'uncommon', price: 72, phases: ['dusk'], diff: 2.4, where: ['bay'],
    size: [12, 25], map: 'jelly', pal: { j: '#c0f0ff', h: '#ffffff', k: OUTLINE, m: '#7ad0f0', l: '#a0e0f8', t: '#e0f8ff' },
    blurb: 'Clear as ice. You can see what it had for lunch.' },
  { id: 'penguinperch', name: 'Penguin Perch', rarity: 'uncommon', price: 60, phases: ['sunrise', 'sunset'], diff: 2.3, where: ['bay'],
    size: [15, 30], len: 13, h: 8, pattern: 'none',
    body: '#3a3a4a', belly: '#ffffff', fin: '#2a2a3a', accent: '#ffb040',
    blurb: 'Dressed for a fancy party it was never invited to.' },
  { id: 'moonhalibut', name: 'Moonice Halibut', rarity: 'rare', price: 200, phases: ['night'], diff: 4.0, where: ['bay'],
    size: [80, 150], len: 16, h: 11, shape: 'round', pattern: 'spots',
    body: '#c8d0e8', belly: '#f8f8ff', fin: '#9aa8d0', accent: '#ffffff',
    blurb: 'Flat, silver, and shaped like a slice of the moon.' },
  { id: 'snowglobetrout', name: 'Snowglobe Trout', rarity: 'rare', price: 185, phases: ['day', 'dusk'], diff: 3.9, where: ['bay'],
    size: [30, 60], len: 16, h: 7, pattern: 'stars',
    body: '#7ab0e0', belly: '#e8f4ff', fin: '#5a90c0', accent: '#ffffff',
    blurb: 'It\'s always snowing a little bit, just around it.' },
  { id: 'pinknarwhal', name: 'Pink Narwhal', rarity: 'rare', price: 230, phases: ['golden'], diff: 4.4, where: ['bay'],
    size: [150, 300], map: 'narwhal', pal: { n: '#ffb0cc', b: '#e080a8', w: '#fff0f6', k: OUTLINE, h: '#fff3c4', t: '#e080a8' },
    blurb: 'The rarer, pinker cousin. Twice as sparkly.' },
  { id: 'aurorasovereign', name: 'Aurora Sovereign', rarity: 'legendary', price: 1925, phases: ['night'], diff: 5.9, where: ['bay'],
    size: [200, 340], len: 30, shape: 'eel', pattern: 'gradient', whiskers: true,
    body: '#7ae0c0', belly: '#e8fff8', fin: '#b89cff', accent: '#ff9ed8',
    blurb: 'When it surfaces, the whole sky changes colour to say hello.' },
  // Blossom River
  { id: 'dangodace', name: 'Dango Dace', rarity: 'common', price: 18, phases: ALL_DAY, diff: 1.3, where: ['blossom'],
    size: [5, 12], len: 11, h: 6, pattern: 'spots',
    body: '#ffd0e0', belly: '#ffffff', fin: '#8ad08a', accent: '#ffffff',
    blurb: 'Pink, white and green, like its favourite snack.' },
  { id: 'yuzuyellowtail', name: 'Yuzu Yellowtail', rarity: 'common', price: 22, phases: ['day', 'golden'], diff: 1.6, where: ['blossom'],
    size: [25, 50], len: 15, h: 7, pattern: 'gradient',
    body: '#e8e8e0', belly: '#ffffff', fin: '#ffd23f', accent: '#ffd23f',
    blurb: 'A little bit sour. A little bit sweet.' },
  { id: 'bamboobarb', name: 'Bamboo Barb', rarity: 'common', price: 17, phases: ['sunrise', 'day'], diff: 1.3, where: ['blossom'],
    size: [6, 12], len: 11, h: 6, pattern: 'stripes',
    body: '#c8e0a0', belly: '#f0f8e0', fin: '#6a9a4a', accent: '#4a7a3a',
    blurb: 'Grows about an inch a day. Emotionally.' },
  { id: 'lanterntetra', name: 'Paper Lantern Tetra', rarity: 'common', price: 19, phases: ['dusk', 'night'], diff: 1.4, where: ['blossom'],
    size: [4, 8], len: 10, h: 6, pattern: 'none',
    body: '#ff7a5a', belly: '#ffe0c0', fin: '#ffd27a', accent: '#ffd27a',
    blurb: 'Lights up during festivals. And also when happy.' },
  { id: 'tanukigoby', name: 'Tanuki Goby', rarity: 'common', price: 20, phases: ['night', 'sunrise'], diff: 1.5, where: ['blossom'],
    size: [6, 14], len: 11, h: 8, shape: 'round', pattern: 'patches',
    body: '#a08060', belly: '#f0e0c8', fin: '#6a5040', accent: '#3a2a20',
    blurb: 'A mischief-maker. Will swap your bait for a leaf.' },
  { id: 'origamishiner', name: 'Origami Shiner', rarity: 'common', price: 21, phases: ['golden', 'sunset'], diff: 1.5, where: ['blossom'],
    size: [8, 14], len: 12, h: 6, pattern: 'patches',
    body: '#f8f0e8', belly: '#ffffff', fin: '#e0566e', accent: '#7fb8e6',
    blurb: 'Folded from a single sheet of river paper.' },
  { id: 'wavekoi', name: 'Wave Koi', rarity: 'uncommon', price: 68, phases: ['sunrise'], diff: 2.6, where: ['blossom'],
    size: [40, 75], len: 17, h: 8, pattern: 'patches',
    body: '#e8f0ff', belly: '#ffffff', fin: '#3a5a9a', accent: '#3a5a9a',
    blurb: 'Painted in the style of a very famous wave.' },
  { id: 'sakurapuffer', name: 'Sakura Puffer', rarity: 'uncommon', price: 60, phases: ['day', 'golden'], diff: 2.4, where: ['blossom'],
    size: [8, 18], r: 5, shape: 'puffer', pattern: 'spots',
    body: '#ffd0e0', belly: '#fff4f8', fin: '#ff9ec4', accent: '#ffffff',
    blurb: 'Puffs up into a perfect cherry blossom.' },
  { id: 'kitsuneeel', name: 'Kitsune Eel', rarity: 'uncommon', price: 75, phases: ['dusk'], diff: 2.8, where: ['blossom'],
    size: [40, 80], len: 22, shape: 'eel', pattern: 'patches',
    body: '#ffa850', belly: '#fff0d8', fin: '#ffffff', accent: '#ffffff',
    blurb: 'Has nine tail fins. Please don\'t count.' },
  { id: 'senchasalmon', name: 'Sencha Salmon', rarity: 'uncommon', price: 62, phases: ['golden', 'sunset'], diff: 2.5, where: ['blossom'],
    size: [40, 70], len: 16, h: 8, pattern: 'gradient',
    body: '#9ac070', belly: '#f0f8e0', fin: '#6a9050', accent: '#ffb0a0',
    blurb: 'Calm, polite, and bows before swimming away.' },
  { id: 'moonrabbit', name: 'Moon Rabbitfish', rarity: 'rare', price: 195, phases: ['night'], diff: 4.0, where: ['blossom'],
    size: [20, 35], len: 13, h: 10, shape: 'round', pattern: 'spots',
    body: '#f0f0f8', belly: '#ffffff', fin: '#ffb0cc', accent: '#c8c0d8',
    blurb: 'Spends every full moon making mochi.' },
  { id: 'fanfish', name: 'Folding Fan Fish', rarity: 'rare', price: 210, phases: ['sunset'], diff: 4.2, where: ['blossom'],
    size: [15, 30], len: 12, h: 12, shape: 'round', pattern: 'stripes',
    body: '#e0566e', belly: '#fff0e8', fin: '#ffd23f', accent: '#ffd23f',
    blurb: 'Opens its fins like a fan to cool itself off.' },
  { id: 'shrinekoi', name: 'Shrine Keeper Koi', rarity: 'rare', price: 230, phases: ['sunrise', 'dusk'], diff: 4.3, where: ['blossom'],
    size: [60, 110], len: 18, h: 9, pattern: 'patches',
    body: '#ffffff', belly: '#fffafa', fin: '#e0303a', accent: '#e0303a',
    blurb: 'Sweeps the river shrine every morning.' },
  { id: 'hanamidragon', name: 'Hanami Dragon', rarity: 'legendary', price: 1840, phases: ['golden', 'sunset'], diff: 5.9, where: ['blossom'],
    size: [180, 300], len: 30, shape: 'eel', pattern: 'gradient', whiskers: true,
    body: '#ffb0cc', belly: '#fff0f6', fin: '#ffffff', accent: '#e0508a',
    blurb: 'Only appears when the blossoms are at their very best. Brings snacks.' },
  // Ember Isle
  { id: 'charcoalchub', name: 'Charcoal Chub', rarity: 'common', price: 20, phases: ALL_DAY, diff: 1.4, where: ['ember'],
    size: [10, 22], len: 12, h: 7, pattern: 'spots',
    body: '#4a4048', belly: '#8a7a80', fin: '#ff7a3c', accent: '#ff7a3c',
    blurb: 'Glows orange when you blow on it.' },
  { id: 'sparkfry', name: 'Spark Fry', rarity: 'common', price: 18, phases: ['dusk', 'night'], diff: 1.2, where: ['ember'],
    size: [2, 5], len: 9, h: 4, pattern: 'stars',
    body: '#ffb040', belly: '#fff0c0', fin: '#ff6a2a', accent: '#ffffff',
    blurb: 'Crackles a little when it swims.' },
  { id: 'toastedtetra', name: 'Toasted Tetra', rarity: 'common', price: 21, phases: ['golden', 'sunset'], diff: 1.4, where: ['ember'],
    size: [4, 8], len: 10, h: 6, pattern: 'gradient',
    body: '#e0a060', belly: '#fff0d0', fin: '#a06030', accent: '#6a3a1a',
    blurb: 'Golden brown on both sides. Perfect.' },
  { id: 'pumicepuffer', name: 'Pumice Puffer', rarity: 'common', price: 24, phases: ['day'], diff: 1.6, where: ['ember'],
    size: [8, 16], r: 4, shape: 'puffer', pattern: 'spots',
    body: '#b8a8a0', belly: '#e0d8d0', fin: '#8a7a70', accent: '#6a5a50',
    blurb: 'So light it floats. Which is awkward for a fish.' },
  { id: 'salamandergoby', name: 'Salamander Goby', rarity: 'common', price: 23, phases: ['sunrise', 'day'], diff: 1.5, where: ['ember'],
    size: [8, 16], len: 12, h: 6, pattern: 'spots',
    body: '#ff6a3a', belly: '#ffd0a0', fin: '#ffd23f', accent: '#2a1a2e',
    blurb: 'Fireproof, and a little bit smug about it.' },
  { id: 'hotspringhake', name: 'Hot Spring Hake', rarity: 'common', price: 26, phases: ['night', 'sunrise'], diff: 1.7, where: ['ember'],
    size: [20, 40], len: 14, h: 7, pattern: 'none',
    body: '#d8a0a0', belly: '#fff0f0', fin: '#b07070', accent: '#ffffff',
    blurb: 'Soaks for hours. Comes out pink and relaxed.' },
  { id: 'lavalampguppy', name: 'Lava Lamp Guppy', rarity: 'uncommon', price: 70, phases: ['night'], diff: 2.4, where: ['ember'],
    size: [5, 10], len: 10, h: 6, pattern: 'patches',
    body: '#b83a8a', belly: '#ffd0f0', fin: '#ff7a3c', accent: '#ffb040',
    blurb: 'Blobs of colour drift around inside it. Groovy.' },
  { id: 'basaltbass', name: 'Basalt Bass', rarity: 'uncommon', price: 66, phases: ['day', 'golden'], diff: 2.6, where: ['ember'],
    size: [30, 60], len: 16, h: 9, pattern: 'patches',
    body: '#3a3440', belly: '#6a6070', fin: '#2a2430', accent: '#ff7a3c',
    blurb: 'Made of cooled lava. Still a bit warm in the middle.' },
  { id: 'obsidiancrab', name: 'Obsidian Crab', rarity: 'uncommon', price: 72, phases: ['dusk', 'night'], diff: 2.5, where: ['ember'],
    size: [15, 30], map: 'crab', bottom: true, pal: { p: '#3a3440', h: '#8a7a90', l: '#ff7a3c', k: OUTLINE },
    blurb: 'Claws sharp enough to cut glass. Uses them to wave.' },
  { id: 'smokeeel', name: 'Smoke Wisp Eel', rarity: 'uncommon', price: 64, phases: ['sunset', 'dusk'], diff: 2.7, where: ['ember'],
    size: [40, 80], len: 22, shape: 'eel', pattern: 'gradient',
    body: '#8a8090', belly: '#e0d8e8', fin: '#c0b8c8', accent: '#5a5060',
    blurb: 'Drifts through the water like a wisp of smoke.' },
  { id: 'magmamarlin', name: 'Magma Marlin', rarity: 'rare', price: 220, phases: ['day', 'sunset'], diff: 4.2, where: ['ember'],
    size: [150, 280], len: 24, h: 7, pattern: 'gradient', bill: true,
    body: '#2a2430', belly: '#ff7a3c', fin: '#ffd23f', accent: '#ff4a2a',
    blurb: 'Its bill toasts marshmallows. Please ask first.' },
  { id: 'firecrackerpuffer', name: 'Firecracker Puffer', rarity: 'rare', price: 190, phases: ['night'], diff: 4.0, where: ['ember'],
    size: [10, 25], r: 6, shape: 'puffer', pattern: 'stars',
    body: '#e0303a', belly: '#ffd0a0', fin: '#ffd23f', accent: '#ffffff',
    blurb: 'Goes off with a pop. Then apologises.' },
  { id: 'emberaxolotl', name: 'Ember Axolotl', rarity: 'rare', price: 205, phases: ['dusk'], diff: 4.1, where: ['ember'],
    size: [15, 30], map: 'axolotl', bottom: true, pal: { g: '#ff6a3a', a: '#ffd0a0', k: OUTLINE, m: '#e04a2a', t: '#ffd23f' },
    blurb: 'Its frills glow like embers. Loves a warm bath.' },
  { id: 'calderakoi', name: 'Caldera Koi', rarity: 'legendary', price: 2010, phases: ['night', 'dusk'], diff: 6.0, where: ['ember'],
    size: [100, 180], len: 20, h: 10, pattern: 'patches',
    body: '#2a2430', belly: '#6a5a60', fin: '#ffd23f', accent: '#ff5a2a',
    blurb: 'Lives in the heart of the volcano. Swims up now and then to cool off.' },
  // Cloud Lake
  { id: 'cumuluscarp', name: 'Cumulus Carp', rarity: 'common', price: 24, phases: ALL_DAY, diff: 1.5, where: ['cloud'],
    size: [15, 30], len: 13, h: 10, shape: 'round', pattern: 'none',
    body: '#ffffff', belly: '#f0f4ff', fin: '#c8d8f0', accent: '#c8d8f0',
    blurb: 'Mostly made of cloud. Very fluffy. Slightly damp.' },
  { id: 'raindropdanio', name: 'Raindrop Danio', rarity: 'common', price: 20, phases: ['day', 'dusk'], diff: 1.2, where: ['cloud'],
    size: [3, 6], len: 9, h: 5, pattern: 'spots',
    body: '#a0c8f0', belly: '#f0f8ff', fin: '#6a9ad0', accent: '#ffffff',
    blurb: 'Falls from the clouds with every drizzle.' },
  { id: 'kitefish', name: 'Kite Fish', rarity: 'common', price: 25, phases: ['golden', 'sunset'], diff: 1.6, where: ['cloud'],
    size: [15, 25], len: 12, h: 11, shape: 'round', pattern: 'stripes',
    body: '#ffd23f', belly: '#fff8d0', fin: '#e0566e', accent: '#e0566e',
    blurb: 'Catches the wind and goes wherever it likes.' },
  { id: 'windchimeminnow', name: 'Windchime Minnow', rarity: 'common', price: 22, phases: ['sunrise', 'day'], diff: 1.3, where: ['cloud'],
    size: [4, 8], len: 10, h: 5, pattern: 'stripes',
    body: '#e0e8f0', belly: '#ffffff', fin: '#b0c0d8', accent: '#8aa0c0',
    blurb: 'Tinkles softly when the breeze blows.' },
  { id: 'breezebream', name: 'Breeze Bream', rarity: 'common', price: 26, phases: ['dusk', 'night'], diff: 1.6, where: ['cloud'],
    size: [15, 30], len: 12, h: 10, shape: 'round', pattern: 'gradient',
    body: '#c8b8f0', belly: '#f8f0ff', fin: '#9a8ae0', accent: '#7fb8e6',
    blurb: 'Just going with the flow.' },
  { id: 'featherfin', name: 'Featherfin', rarity: 'common', price: 28, phases: ['sunrise', 'golden'], diff: 1.8, where: ['cloud'],
    size: [10, 20], len: 13, h: 7, pattern: 'patches',
    body: '#fff0e0', belly: '#ffffff', fin: '#ffb0a0', accent: '#b0a0d8',
    blurb: 'Has feathers instead of scales. Nobody has asked why.' },
  { id: 'hotairpuffer', name: 'Hot Air Puffer', rarity: 'uncommon', price: 75, phases: ['day', 'golden'], diff: 2.5, where: ['cloud'],
    size: [15, 30], r: 6, shape: 'puffer', pattern: 'stripes',
    body: '#e0566e', belly: '#ffe0e8', fin: '#ffd23f', accent: '#ffd23f',
    blurb: 'Takes passengers. Small ones.' },
  { id: 'stormsnapper', name: 'Stormcloud Snapper', rarity: 'uncommon', price: 70, phases: ['night', 'dusk'], diff: 2.7, where: ['cloud'],
    size: [30, 55], len: 15, h: 9, pattern: 'stars',
    body: '#5a6080', belly: '#a0a8c8', fin: '#3a4060', accent: '#ffd23f',
    blurb: 'Grumbles like thunder. Harmless, really.' },
  { id: 'skyjelly', name: 'Sky Jelly', rarity: 'uncommon', price: 78, phases: ['day'], diff: 2.3, where: ['cloud'],
    size: [15, 30], map: 'jelly', pal: { j: '#b8e0ff', h: '#ffffff', k: OUTLINE, m: '#7ab0e8', l: '#a0c8f0', t: '#e0f0ff' },
    blurb: 'Lighter than air. Barely.' },
  { id: 'sunbeamtrout', name: 'Sunbeam Trout', rarity: 'uncommon', price: 72, phases: ['sunrise', 'day'], diff: 2.6, where: ['cloud'],
    size: [30, 55], len: 16, h: 7, pattern: 'gradient',
    body: '#fff3a0', belly: '#fffbe0', fin: '#ffd23f', accent: '#ffb040',
    blurb: 'Warm to hold, like a sunny windowsill.' },
  { id: 'starseahorse', name: 'Starlight Seahorse', rarity: 'rare', price: 230, phases: ['night'], diff: 4.1, where: ['cloud'],
    size: [12, 25], map: 'seahorse', pal: { s: '#6a6ab8', b: '#c8c8f0', f: '#fff3a0', e: OUTLINE },
    blurb: 'Gallops across the sky lake on clear nights.' },
  { id: 'rainboweel', name: 'Rainbow Eel', rarity: 'rare', price: 240, phases: ['sunrise', 'golden'], diff: 4.3, where: ['cloud'],
    size: [60, 120], len: 24, shape: 'eel', pattern: 'stripes',
    body: '#ff9ec4', belly: '#fff0f6', fin: '#7ad0e0', accent: '#ffd23f',
    blurb: 'Appears right after it rains. Every single time.' },
  { id: 'zephyrkoi', name: 'Zephyr Koi', rarity: 'rare', price: 215, phases: ['dusk'], diff: 4.0, where: ['cloud'],
    size: [50, 90], len: 17, h: 8, pattern: 'patches',
    body: '#e8f0ff', belly: '#ffffff', fin: '#b89cff', accent: '#7fb8e6',
    blurb: 'Rides the west wind. Never late, never early.' },
  { id: 'celestialcarp', name: 'Celestial Carp', rarity: 'legendary', price: 2190, phases: ['night', 'sunrise'], diff: 6.0, where: ['cloud'],
    size: [120, 220], len: 20, h: 10, pattern: 'stars',
    body: '#2a2a5a', belly: '#6a6aa0', fin: '#fff3a0', accent: '#ffffff',
    blurb: 'Swam up the waterfall, then kept going, all the way to the stars.' },

  { id: 'lebron', name: 'LeBron James', rarity: 'goat', price: 2323, phases: ALL_DAY, diff: 6.5, where: EVERYWHERE,
    weight: 0.35, size: [203, 206], map: 'lebron', bottom: true, unsellable: true,
    blurb: 'This is not a fish. This is LeBron James. Nobody knows how he got in the water. He seems fine with it. He is not for sale.' },
];

// ---------------------------------------------------------- the angler --
const SKIN_TONES = ['#ffe3cc', '#f5c6a0', '#dca27a', '#a8704c', '#6e4430'];
const HAIR_COLORS = ['#3b2433', '#7a4a32', '#e0a050', '#f07a5a', '#ff9ec4', '#9b86e0', '#8fd1c0', '#f4efe6'];
const TOP_COLORS = ['#ff8a6b', '#ffc15e', '#8fd19e', '#7fb8e6', '#c79bf2', '#f4efe6', '#e0566e', '#6a5a9a'];

// Everything with price 0 is free from the start.
const COSMETICS = {
  hair: [
    { id: 'short', name: 'Short', price: 0 },
    { id: 'bob', name: 'Bob', price: 0 },
    { id: 'spiky', name: 'Spiky', price: 0 },
    { id: 'long', name: 'Long', price: 45 },
    { id: 'pigtails', name: 'Pigtails', price: 60 },
    { id: 'bun', name: 'Bun', price: 60 },
    { id: 'curly', name: 'Big curls', price: 700 },
    { id: 'mohawk', name: 'Mohawk', price: 1200 },
    { id: 'sidetail', name: 'Side ponytail', price: 1500 },
  ],
  hat: [
    { id: 'none', name: 'No hat', price: 0 },
    { id: 'straw', name: 'Straw hat', price: 0 },
    { id: 'beanie', name: 'Beanie', price: 40 },
    { id: 'bucket', name: 'Bucket hat', price: 75 },
    { id: 'cat', name: 'Cat ears', price: 120 },
    { id: 'flower', name: 'Flower crown', price: 180 },
    { id: 'frog', name: 'Frog hat', price: 260 },
    { id: 'fishhat', name: 'Fish hat', price: 500 },
    { id: 'crown', name: 'Crown', price: 700 },
    { id: 'party', name: 'Party hat', price: 900 },
    { id: 'chef', name: "Chef's hat", price: 1200 },
    { id: 'pirate', name: 'Pirate hat', price: 2100 },
    { id: 'wizard', name: 'Wizard hat', price: 3000 },
    { id: 'tophat', name: 'Top hat', price: 4800 },
    { id: 'halo', name: 'Halo', price: 7200 },
    { id: 'diamondcrown', name: 'Diamond crown', price: 18000 },
  ],
  top: [
    { id: 'tee', name: 'Tee', price: 0 },
    { id: 'sweater', name: 'Sweater', price: 30 },
    { id: 'overalls', name: 'Overalls', price: 80 },
    { id: 'hoodie', name: 'Hoodie', price: 110 },
    { id: 'raincoat', name: 'Raincoat', price: 160 },
    { id: 'sailor', name: 'Sailor top', price: 240 },
    { id: 'kimono', name: 'Kimono', price: 900 },
    { id: 'tux', name: 'Tuxedo', price: 2400 },
    { id: 'goldjacket', name: 'Gold jacket', price: 5400 },
    { id: 'robe', name: 'Royal robe', price: 12000 },
  ],
  face: [
    { id: 'blush', name: 'Blush', price: 0 },
    { id: 'plain', name: 'Plain', price: 0 },
    { id: 'freckles', name: 'Freckles', price: 20 },
    { id: 'glasses', name: 'Glasses', price: 70 },
    { id: 'shades', name: 'Heart shades', price: 220 },
    { id: 'mustache', name: 'Moustache', price: 800 },
    { id: 'monocle', name: 'Monocle', price: 1500 },
    { id: 'starshades', name: 'Star shades', price: 3000 },
    { id: 'diamondshades', name: 'Diamond shades', price: 9000 },
  ],
  buddy: [
    { id: 'none', name: 'No buddy', price: 0 },
    { id: 'duck', name: 'Duck', price: 200 },
    { id: 'cat', name: 'Cat', price: 320 },
    { id: 'frog', name: 'Frog', price: 380 },
    { id: 'capy', name: 'Capybara', price: 700 },
    { id: 'bunny', name: 'Bunny', price: 850 },
    { id: 'penguin', name: 'Penguin', price: 900 },
    { id: 'fox', name: 'Fox', price: 1300 },
    { id: 'panda', name: 'Panda', price: 1800 },
    { id: 'axolotl', name: 'Axolotl', price: 2400 },
    { id: 'corgi', name: 'Corgi', price: 3000 },
    { id: 'otter', name: 'Otter (with clam)', price: 3900 },
    { id: 'redpanda', name: 'Red panda', price: 4800 },
    { id: 'ghost', name: 'Friendly ghost', price: 6000 },
    { id: 'dragon', name: 'Baby dragon', price: 9000 },
    { id: 'unicorn', name: 'Unicorn', price: 15000 },
    { id: 'goldduck', name: 'Golden duck', price: 30000 },
  ],
};

const COSMETIC_TABS = [
  { id: 'hair', label: 'Hair' },
  { id: 'hat', label: 'Hats' },
  { id: 'top', label: 'Tops' },
  { id: 'face', label: 'Face' },
  { id: 'buddy', label: 'Buddy' },
  { id: 'colors', label: 'Colours' },
];

const DEFAULT_LOOK = {
  skin: 1, hairColor: 1, topColor: 0,
  hair: 'bob', hat: 'straw', top: 'tee', face: 'blush', buddy: 'none',
};

// -------------------------------------------------------------- the boat --
// Shown at every spot except the home dock (where it's tied up), while
// sailing, and on the sea chart. Everything with price 0 is free from the start.
// usesColor: the hull and stripe colours paint this style (others have their own look)
const BOAT_PARTS = {
  base: [
    { id: 'rowboat', name: 'Rowboat', price: 0, usesColor: true },
    { id: 'box', name: 'Cardboard box', price: 40 },
    { id: 'banana', name: 'Banana', price: 120 },
    { id: 'watermelon', name: 'Watermelon', price: 150 },
    { id: 'bathtub', name: 'Bathtub', price: 220, usesColor: true },
    { id: 'teacup', name: 'Teacup', price: 260, usesColor: true },
    { id: 'sneaker', name: 'Big sneaker', price: 300, usesColor: true },
    { id: 'swan', name: 'Swan boat', price: 400 },
    { id: 'duck', name: 'Duck parade', price: 600 },
    { id: 'yacht', name: 'Yacht', price: 7200, usesColor: true },
    { id: 'royal', name: 'Royal barge', price: 24000 },
  ],
  hull: [
    { id: 'coral', name: 'Coral', price: 0, color: '#e0566e' },
    { id: 'sky', name: 'Sky', price: 0, color: '#6aa8e0' },
    { id: 'mint', name: 'Mint', price: 0, color: '#5cc49a' },
    { id: 'cream', name: 'Cream', price: 30, color: '#f0dcc0' },
    { id: 'lilac', name: 'Lilac', price: 60, color: '#b48ae0' },
    { id: 'sunshine', name: 'Sunshine', price: 90, color: '#ffc83a' },
    { id: 'midnight', name: 'Midnight', price: 150, color: '#3e3a80' },
    { id: 'gold', name: 'Solid gold', price: 900, color: '#ffd23f', shiny: true },
    { id: 'obsidian', name: 'Obsidian', price: 1800, color: '#2a2430' },
    { id: 'rosegold', name: 'Rose gold', price: 4800, color: '#e8a090', shiny: true },
    { id: 'diamond', name: 'Diamond', price: 15000, color: '#c8f0ff', shiny: true },
  ],
  trim: [
    { id: 'cream', name: 'Cream', price: 0, color: '#fff4e0' },
    { id: 'navy', name: 'Navy', price: 0, color: '#3a4a8a' },
    { id: 'pink', name: 'Pink', price: 20, color: '#ff9ec4' },
    { id: 'mint', name: 'Mint', price: 20, color: '#8fe0c0' },
    { id: 'gold', name: 'Gold', price: 60, color: '#ffd23f' },
    { id: 'platinum', name: 'Platinum', price: 1500, color: '#e8f0f8' },
    { id: 'ruby', name: 'Ruby', price: 2400, color: '#e0303a' },
    { id: 'emerald', name: 'Emerald', price: 2400, color: '#2ea86a' },
  ],
  sail: [
    { id: 'plain', name: 'Plain sail', price: 0 },
    { id: 'stripes', name: 'Striped', price: 60 },
    { id: 'heart', name: 'Heart', price: 120 },
    { id: 'star', name: 'Star', price: 180 },
    { id: 'fish', name: 'Fish', price: 250 },
    { id: 'rainbow', name: 'Rainbow sail', price: 1800 },
    { id: 'gold', name: 'Golden sail', price: 4800 },
    { id: 'crown', name: 'Royal crest', price: 9000 },
  ],
  flag: [
    { id: 'none', name: 'No flag', price: 0 },
    { id: 'pennant', name: 'Pennant', price: 30 },
    { id: 'heart', name: 'Heart flag', price: 80 },
    { id: 'pirate', name: 'Pirate', price: 150 },
    { id: 'fish', name: 'Fish flag', price: 200 },
    { id: 'crown', name: 'Crown flag', price: 1500 },
    { id: 'rainbow', name: 'Rainbow flag', price: 2400 },
    { id: 'goat', name: 'GOAT flag', price: 7200 },
  ],
  decor: [
    { id: 'none', name: 'Nothing', price: 0 },
    { id: 'fern', name: 'Potted fern', price: 50 },
    { id: 'flowers', name: 'Flower box', price: 70 },
    { id: 'duck', name: 'Rubber duck', price: 90 },
    { id: 'lights', name: 'String lights', price: 160 },
    { id: 'fireworks', name: 'Fireworks', price: 3600 },
    { id: 'treasure', name: 'Treasure hoard', price: 9000 },
  ],
};

const BOAT_TABS = [
  { id: 'base', label: 'Style' },
  { id: 'hull', label: 'Colour' },
  { id: 'trim', label: 'Stripe' },
  { id: 'sail', label: 'Sail' },
  { id: 'flag', label: 'Flag' },
  { id: 'decor', label: 'Decor' },
];

const DEFAULT_BOAT = { base: 'rowboat', hull: 'coral', trim: 'cream', sail: 'plain', flag: 'none', decor: 'none' };

// ------------------------------------------------------------- the gear --
// net: radius of your net in the underwater chase (in pixels)
// gain: how fast the catch bar fills while the fish is in your net
// luck: shifts odds toward rare fish and bigger sizes
// wait: multiplier on how long fish take to notice your bobber
// net: radius of the chase net. gain: how fast the bar fills. grip: how much
// of the drain you feel when it slips out. netSpeed: how fast you can move the
// net (pixels a second). calm: how much slower the bar drains on big fish
// (fully on legendaries, half on rares, a bit more than that on LeBron). sparkle: a twinkle at
// the rod tip. Rods never slow the fish down.
const RODS = [
  { id: 'twig', name: 'Twig Rod', color: '#7a4a2a', price: 0, net: 16, gain: 0.34, grip: 0.88, netSpeed: 150, calm: 0, luck: 0, wait: 1,
    blurb: 'A stick, some string, and a lot of hope. Rare fish laugh at it.' },
  { id: 'bamboo', name: 'Bamboo Rod', color: '#c8a050', price: 90, net: 18, gain: 0.38, grip: 0.64, netSpeed: 175, calm: 0.08, luck: 0.05, wait: 0.9,
    blurb: 'Bendy and dependable. A bigger net for chasing.' },
  { id: 'sunset', name: 'Sunset Rod', color: '#ff7a5c', price: 350, net: 20, gain: 0.42, grip: 0.57, netSpeed: 185, calm: 0.16, luck: 0.12, wait: 0.8,
    blurb: 'Painted the colour of the sky. Reels in fast and holds on tight.' },
  { id: 'star', name: 'Star Rod', color: '#b89cff', price: 3500, net: 23, gain: 0.5, grip: 0.44, netSpeed: 210, calm: 0.22, luck: 0.25, wait: 0.7, sparkle: '#fff3c4',
    blurb: 'Hums quietly at night. A big net that goes where you point it.' },
  { id: 'aurora', name: 'Aurora Rod', color: '#7ae0c0', price: 10000, net: 25, gain: 0.54, grip: 0.36, netSpeed: 235, calm: 0.28, luck: 0.3, wait: 0.65, sparkle: '#b89cff',
    blurb: 'Spun from the northern lights. The net practically flies.' },
  { id: 'goat', name: 'GOAT Rod', color: '#ffd23f', price: 30000, net: 28, gain: 0.6, grip: 0.28, netSpeed: 265, calm: 0.34, luck: 0.35, wait: 0.6, sparkle: '#ffffff',
    blurb: 'Solid gold. Signed by a certain basketball player. The best there is.' },
];

const TANKS = [
  { cap: 6, price: 0, name: 'Fishbowl' },
  { cap: 12, price: 180, name: 'Glass tank' },
  { cap: 24, price: 600, name: 'Grand aquarium' },
  { cap: 40, price: 3600, name: 'Royal aquarium' },
  { cap: 64, price: 18000, name: 'Ocean palace' },
];

// ---------------------------------------------------------------- home --
// Your room: a wall and a floor you can restyle, furniture you drag into
// place, and all your tanks. The room canvas is HOME_W x HOME_H pixels; the
// wall runs down to HOME_FLOOR, where the floor starts.
const HOME_W = 320, HOME_H = 180, HOME_FLOOR = 64;
const MAX_TANKS = 7;
// What each extra tank costs (the first one is yours from the start).
const TANK_PRICES = [0, 900, 2400, 5400, 12000, 24000, 48000];
const MAX_FURNITURE = 40;

// wall: hangs on the wall (otherwise it stands on the floor). w/h in room pixels.
const FURNITURE = [
  { id: 'plant', name: 'Potted plant', price: 60, w: 12, h: 20, blurb: 'Leafy and low-maintenance.' },
  { id: 'rug', name: 'Round rug', price: 80, w: 48, h: 22, blurb: 'Ties the room together.' },
  { id: 'lamp', name: 'Floor lamp', price: 120, w: 10, h: 34, blurb: 'Warm light for reading fish books.' },
  { id: 'painting', name: 'Sunset painting', price: 150, w: 26, h: 18, wall: true, blurb: 'A painting of a dock at sunset. Familiar.' },
  { id: 'chair', name: 'Cosy chair', price: 150, w: 18, h: 22, blurb: 'Perfect for watching the tank.' },
  { id: 'table', name: 'Little table', price: 200, w: 24, h: 16, blurb: 'Holds a teapot and a very small vase.' },
  { id: 'clock', name: 'Wall clock', price: 250, w: 14, h: 14, wall: true, blurb: 'Tick, tock, fish o\'clock.' },
  { id: 'beanbag', name: 'Beanbag', price: 300, w: 22, h: 14, blurb: 'Impossible to get out of.' },
  { id: 'bookshelf', name: 'Bookshelf', price: 350, w: 24, h: 38, blurb: 'Mostly fishing guides. One romance novel.' },
  { id: 'lights', name: 'Fairy lights', price: 400, w: 60, h: 8, wall: true, blurb: 'Twinkle twinkle.' },
  { id: 'bed', name: 'Bed', price: 500, w: 44, h: 22, blurb: 'Sheets with little fish on them.' },
  { id: 'mirror', name: 'Round mirror', price: 700, w: 16, h: 20, wall: true, blurb: 'Looking good, angler.' },
  { id: 'sofa', name: 'Sofa', price: 800, w: 46, h: 22, blurb: 'Seats three. Or one buddy, sprawled.' },
  { id: 'fireplace', name: 'Fireplace', price: 1500, w: 34, h: 32, blurb: 'Crackles. Keeps the tanks toasty.' },
  { id: 'poster', name: 'GOAT poster', price: 2323, w: 18, h: 24, wall: true, blurb: 'A signed poster. Guess who.' },
  { id: 'piano', name: 'Piano', price: 3600, w: 38, h: 30, blurb: 'Plays one song. It is a sea shanty.' },
  { id: 'arcade', name: 'Arcade cabinet', price: 5400, w: 20, h: 40, blurb: 'A fishing game inside a fishing game.' },
  { id: 'trophyfish', name: 'Golden fish plaque', price: 7200, w: 30, h: 16, wall: true, blurb: 'For the one that did not get away.' },
  { id: 'chandelier', name: 'Chandelier', price: 15000, w: 30, h: 22, wall: true, blurb: 'Fancy. Very fancy.' },
  { id: 'throne', name: 'Golden throne', price: 36000, w: 26, h: 40, blurb: 'Fit for the ruler of the pond.' },
];
const FURNITURE_BY_ID = Object.fromEntries(FURNITURE.map(f => [f.id, f]));
// how big a tank looks in the room, by its size level
const TANK_ROOM_W = [26, 32, 40, 48, 58];

const WALLPAPERS = [
  { id: 'cream', name: 'Cream', price: 0, a: '#f4e6d0', b: '#ecdcc2' },
  { id: 'peach', name: 'Peach stripes', price: 200, a: '#ffd6c0', b: '#ffc4a8', stripes: true },
  { id: 'sky', name: 'Sky blue', price: 400, a: '#cfe6f6', b: '#bcd8ee' },
  { id: 'mint', name: 'Mint dots', price: 800, a: '#d4f0dc', b: '#a8dcb8', dots: true },
  { id: 'lilac', name: 'Lilac stripes', price: 900, a: '#e4d4f6', b: '#d4c0f0', stripes: true },
  { id: 'night', name: 'Starry night', price: 3000, a: '#2a2a5a', b: '#fff3a0', stars: true },
  { id: 'gold', name: 'Gold damask', price: 12000, a: '#f0d080', b: '#e0b040', dots: true },
];
const FLOORS = [
  { id: 'wood', name: 'Wood', price: 0, a: '#c08a5a', b: '#a8744a' },
  { id: 'checker', name: 'Checkerboard', price: 300, a: '#f4efe6', b: '#e0566e', checker: true },
  { id: 'carpet', name: 'Pink carpet', price: 600, a: '#f0a8c0', b: '#e898b4' },
  { id: 'tile', name: 'Sea tiles', price: 900, a: '#a8d8e0', b: '#88c0d0', checker: true },
  { id: 'marble', name: 'Marble', price: 4800, a: '#f4f4f8', b: '#d8d8e4' },
  { id: 'goldtile', name: 'Gold tiles', price: 15000, a: '#ffd23f', b: '#e0a020', checker: true },
];

// Buckets hold the fish you're carrying (to sell, or move to the tank later).
const BUCKETS = [
  { cap: 6, price: 0, name: 'Tin pail' },
  { cap: 12, price: 110, name: 'Big bucket' },
  { cap: 24, price: 400, name: 'Cooler' },
  { cap: 40, price: 2400, name: 'Treasure chest' },
  { cap: 64, price: 12000, name: 'Golden barrel' },
];

// Enchantments: now and then one is tangled on the line with a catch
// (ENCHANT_CHANCE per catch). You keep them until you choose to use one.
// While it lasts, luck adds to your rod's luck and net to its net size.
// secs counts fishing time, so it doesn't run down while a menu is open.
const ENCHANT_CHANCE = 0.06;
const ENCHANTS = [
  { id: 'clover', name: 'Clover Charm', luck: 0.1, net: 0, secs: 90, weight: 45, color: '#7ac070',
    blurb: 'A four-leaf clover in a tiny bottle. Rare fish bite more often.' },
  { id: 'rune', name: 'Wide Net Rune', luck: 0, net: 5, secs: 90, weight: 35, color: '#7fb8e6',
    blurb: 'Draw it on your net and the net grows.' },
  { id: 'pearl', name: 'Tide Pearl', luck: 0.25, net: 0, secs: 60, weight: 12, color: '#ffb0d8',
    blurb: 'Hums with the tide. Legendary fish can hear it.' },
  { id: 'elixir', name: 'Starlight Elixir', luck: 0.15, net: 5, secs: 120, weight: 8, color: '#b89cff',
    blurb: 'Luck and a bigger net at once, and it lasts longer.' },
];
const ENCHANT_BY_ID = Object.fromEntries(ENCHANTS.map(e => [e.id, e]));
const MAX_BOOST_SECS = 600;  // the most time one kind of boost can stack up to

// The aquarium canvas, in pixels, and where its sand starts.
const TANK_W = 240, TANK_H = 135, TANK_SAND = TANK_H - 14;

// Props for the tank, bought in the Shop and dragged into place in the Tank.
// w and h are the prop's size in tank pixels (the tank is 240 x 135). Props
// sit on the sand unless they float, which lets them go anywhere in the water.
// The pixel art for each one is drawDecor() in ui.js.
const DECOR = [
  { id: 'castle', name: 'Sandcastle', price: 0, w: 32, h: 44, blurb: 'Every tank starts with one.' },
  { id: 'chest', name: 'Treasure chest', price: 0, w: 16, h: 12, blurb: 'Burps a bubble now and then.' },
  { id: 'kelp', name: 'Kelp', price: 0, w: 8, h: 36, blurb: 'Sways in a current that isn\'t there.' },
  { id: 'starfish', name: 'Starfish', price: 25, w: 10, h: 5, blurb: 'Has been lying there all day. Living the dream.' },
  { id: 'pinkweed', name: 'Pink seaweed', price: 35, w: 8, h: 26, blurb: 'Kelp, but make it fashion.' },
  { id: 'coral', name: 'Peach coral', price: 60, w: 20, h: 20, blurb: 'Fish love hiding behind it.' },
  { id: 'clam', name: 'Pearl clam', price: 80, w: 16, h: 9, blurb: 'Opens up to show off its pearl.' },
  { id: 'sign', name: 'Welcome sign', price: 70, w: 20, h: 16, blurb: 'Says "home" in fish.' },
  { id: 'arch', name: 'Rock arch', price: 90, w: 34, h: 20, blurb: 'For swimming through, dramatically.' },
  { id: 'duck', name: 'Rubber duck', price: 120, w: 14, h: 11, float: true, blurb: 'Floats. Squeaks. Judges.' },
  { id: 'diver', name: 'Tiny diver', price: 150, w: 12, h: 18, blurb: 'Looking for treasure. It\'s right there.' },
  { id: 'jelly', name: 'Jellyfish lamp', price: 180, w: 12, h: 16, float: true, blurb: 'A gentle night light that drifts.' },
  { id: 'pineapple', name: 'Pineapple house', price: 200, w: 18, h: 28, blurb: 'Someone very cheerful lives here.' },
  { id: 'volcano', name: 'Bubble volcano', price: 220, w: 24, h: 16, blurb: 'Erupts in bubbles. Very safe.' },
  { id: 'wreck', name: 'Little shipwreck', price: 280, w: 46, h: 24, blurb: 'Nobody knows what happened. (A duck did it.)' },
  { id: 'trophy', name: 'GOAT trophy', price: 400, w: 14, h: 20, blurb: 'For the tank that has everything.' },
  { id: 'rainbowcoral', name: 'Rainbow coral', price: 1800, w: 21, h: 22, blurb: 'Every colour at once. Very loud. Very lovely.' },
  { id: 'crystal', name: 'Crystal cluster', price: 4800, w: 18, h: 22, blurb: 'Hums a little at night. The fish find it soothing.' },
  { id: 'goldcastle', name: 'Golden castle', price: 9000, w: 32, h: 44, blurb: 'The sandcastle, but make it treasure.' },
  { id: 'hoard', name: 'Treasure hoard', price: 15000, w: 30, h: 17, blurb: 'A dragon would be jealous.' },
  { id: 'statue', name: 'Golden fish statue', price: 30000, w: 20, h: 31, blurb: 'A monument to the one that got away. It did not get away.' },
];
const DECOR_BY_ID = Object.fromEntries(DECOR.map(d => [d.id, d]));
const MAX_DECOR = 30;  // props placed in the tank at once

// The tank everyone starts with (and what older saves get): x is the prop's
// centre, y its bottom, both in tank pixels.
const STARTER_DECOR = [
  { id: 'kelp', x: 9, y: 121 }, { id: 'castle', x: 37, y: 121 }, { id: 'kelp', x: 71, y: 121 },
  { id: 'kelp', x: 151, y: 121 }, { id: 'chest', x: 198, y: 121 }, { id: 'kelp', x: 225, y: 121 },
];

